// Component categories and definitions for MIT App Inventor
// Each component has: type, version, category, icon (emoji), properties, events, methods
// Used by the visual designer and AIA generator.

export const CATEGORIES = [
  { id: 'ui', name: 'User Interface', icon: '🖥️' },
  { id: 'layout', name: 'Layout', icon: '📐' },
  { id: 'media', name: 'Media', icon: '🎵' },
  { id: 'drawing', name: 'Drawing & Animation', icon: '🎨' },
  { id: 'sensors', name: 'Sensors', icon: '📡' },
  { id: 'social', name: 'Social', icon: '📱' },
  { id: 'storage', name: 'Storage', icon: '💾' },
  { id: 'connectivity', name: 'Connectivity', icon: '🌐' },
];

export const COMPONENTS = {

  // ==========================================================================
  // USER INTERFACE
  // ==========================================================================

  Button: {
    type: 'Button',
    version: '7',
    category: 'ui',
    icon: '🔘',
    defaultName: 'Button',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Button' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Shape: { type: 'number', default: '0' },
      Image: { type: 'asset', default: '' },
      TextAlignment: { type: 'number', default: '1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Click', 'GotFocus', 'LostFocus', 'LongClick', 'TouchDown', 'TouchUp'],
    methods: {},
  },

  Label: {
    type: 'Label',
    version: '5',
    category: 'ui',
    icon: '🏷️',
    defaultName: 'Label',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Label' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      TextAlignment: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
      HTMLFormat: { type: 'boolean', default: 'False' },
      HasMargins: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {},
  },

  TextBox: {
    type: 'TextBox',
    version: '14',
    category: 'ui',
    icon: '📝',
    defaultName: 'TextBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: '' },
      Hint: { type: 'string', default: '' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      MultiLine: { type: 'boolean', default: 'False' },
      NumbersOnly: { type: 'boolean', default: 'False' },
      ReadOnly: { type: 'boolean', default: 'False' },
      TextAlignment: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['GotFocus', 'LostFocus'],
    methods: {},
  },

  CheckBox: {
    type: 'CheckBox',
    version: '2',
    category: 'ui',
    icon: '☑️',
    defaultName: 'CheckBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'CheckBox' },
      Checked: { type: 'boolean', default: 'False' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Changed', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  Image: {
    type: 'Image',
    version: '6',
    category: 'ui',
    icon: '🖼️',
    defaultName: 'Image',
    isVisible: true,
    isLayout: false,
    properties: {
      Picture: { type: 'asset', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      ScalePictureToFit: { type: 'boolean', default: 'False' },
      Visible: { type: 'boolean', default: 'True' },
      ClickableImageBase: { type: 'boolean', default: 'False' },
      Rotation: { type: 'number', default: '0.0' },
      Animation: { type: 'string', default: '' },
    },
    events: ['Click'],
    methods: {},
  },

  ListPicker: {
    type: 'ListPicker',
    version: '9',
    category: 'ui',
    icon: '📋',
    defaultName: 'ListPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Title: { type: 'string', default: '' },
      Text: { type: 'string', default: 'ListPicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      ItemBackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      ItemTextColor: { type: 'color', default: '&HFF000000' },
      ShowFilterBar: { type: 'boolean', default: 'False' },
    },
    events: ['BeforePicking', 'AfterPicking', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  ListView: {
    type: 'ListView',
    version: '10',
    category: 'ui',
    icon: '📃',
    defaultName: 'ListView',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&HFF000000' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      TextSize: { type: 'number', default: '22' },
      SelectionColor: { type: 'color', default: '&HFFCCCCCC' },
      ShowFilterBar: { type: 'boolean', default: 'False' },
    },
    events: ['AfterPicking'],
    methods: {},
  },

  Notifier: {
    type: 'Notifier',
    version: '6',
    category: 'ui',
    icon: '🔔',
    defaultName: 'Notifier',
    isVisible: false,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFF444444' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      NotifierLength: { type: 'number', default: '1' },
    },
    events: ['AfterChoosing', 'AfterTextInput', 'ChoosingCancelled', 'TextInputCancelled'],
    methods: {
      ShowAlert: { params: ['notice'] },
      ShowChooseDialog: { params: ['message', 'title', 'button1Text', 'button2Text', 'cancelable'] },
      ShowTextDialog: { params: ['message', 'title', 'cancelable'] },
      ShowMessageDialog: { params: ['message', 'title', 'buttonText'] },
      ShowProgressDialog: { params: ['message', 'title'] },
      DismissProgressDialog: { params: [] },
      LogError: { params: ['message'] },
      LogInfo: { params: ['message'] },
      LogWarning: { params: ['message'] },
    },
  },

  Slider: {
    type: 'Slider',
    version: '3',
    category: 'ui',
    icon: '🎚️',
    defaultName: 'Slider',
    isVisible: true,
    isLayout: false,
    properties: {
      MinValue: { type: 'number', default: '10' },
      MaxValue: { type: 'number', default: '50' },
      ThumbPosition: { type: 'number', default: '30' },
      Width: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      ColorLeft: { type: 'color', default: '&HFFFF6600' },
      ColorRight: { type: 'color', default: '&HFF888888' },
      ThumbEnabled: { type: 'boolean', default: 'True' },
    },
    events: ['PositionChanged'],
    methods: {},
  },

  Spinner: {
    type: 'Spinner',
    version: '2',
    category: 'ui',
    icon: '🔽',
    defaultName: 'Spinner',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Prompt: { type: 'string', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['AfterSelecting'],
    methods: {},
  },

  Switch: {
    type: 'Switch',
    version: '1',
    category: 'ui',
    icon: '🔀',
    defaultName: 'Switch',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Switch' },
      On: { type: 'boolean', default: 'False' },
      Checked: { type: 'boolean', default: 'False' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      ThumbColorActive: { type: 'color', default: '&HFFFFFFFF' },
      ThumbColorInactive: { type: 'color', default: '&HFFCCCCCC' },
      TrackColorActive: { type: 'color', default: '&HFF00BCD4' },
      TrackColorInactive: { type: 'color', default: '&HFF9E9E9E' },
    },
    events: ['Changed'],
    methods: {},
  },

  DatePicker: {
    type: 'DatePicker',
    version: '4',
    category: 'ui',
    icon: '📅',
    defaultName: 'DatePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'DatePicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['DateSet', 'GotFocus', 'LostFocus'],
    methods: {
      SetDateToDisplay: { params: ['year', 'month', 'day'] },
      LaunchPicker: { params: [] },
    },
  },

  TimePicker: {
    type: 'TimePicker',
    version: '4',
    category: 'ui',
    icon: '⏰',
    defaultName: 'TimePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'TimePicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['TimeSet', 'GotFocus', 'LostFocus'],
    methods: {
      SetTimeToDisplay: { params: ['hour', 'minute'] },
      LaunchPicker: { params: [] },
    },
  },

  PasswordTextBox: {
    type: 'PasswordTextBox',
    version: '7',
    category: 'ui',
    icon: '🔒',
    defaultName: 'PasswordTextBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: '' },
      Hint: { type: 'string', default: '' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      NumbersOnly: { type: 'boolean', default: 'False' },
    },
    events: ['GotFocus', 'LostFocus'],
    methods: {},
  },

  WebViewer: {
    type: 'WebViewer',
    version: '11',
    category: 'ui',
    icon: '🌍',
    defaultName: 'WebViewer',
    isVisible: true,
    isLayout: false,
    properties: {
      HomeUrl: { type: 'string', default: '' },
      CurrentUrl: { type: 'string', default: '' },
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      FollowLinks: { type: 'boolean', default: 'True' },
      IgnoreSslErrors: { type: 'boolean', default: 'False' },
      UsesLocation: { type: 'boolean', default: 'False' },
    },
    events: ['WebViewStringChange', 'PageLoaded', 'BeforePageLoad', 'ErrorOccurred'],
    methods: {
      GoBack: { params: [] },
      GoForward: { params: [] },
      GoHome: { params: [] },
      GoToUrl: { params: ['url'] },
      CanGoBack: { params: [] },
      CanGoForward: { params: [] },
      ClearCaches: { params: [] },
      Reload: { params: [] },
    },
  },

  // ==========================================================================
  // LAYOUT
  // ==========================================================================

  HorizontalArrangement: {
    type: 'HorizontalArrangement',
    version: '4',
    category: 'layout',
    icon: '↔️',
    defaultName: 'HorizontalArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
      Image: { type: 'asset', default: '' },
    },
    events: [],
    methods: {},
  },

  VerticalArrangement: {
    type: 'VerticalArrangement',
    version: '4',
    category: 'layout',
    icon: '↕️',
    defaultName: 'VerticalArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
      Image: { type: 'asset', default: '' },
    },
    events: [],
    methods: {},
  },

  HorizontalScrollArrangement: {
    type: 'HorizontalScrollArrangement',
    version: '2',
    category: 'layout',
    icon: '⬌',
    defaultName: 'HorizontalScrollArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
    },
    events: [],
    methods: {},
  },

  VerticalScrollArrangement: {
    type: 'VerticalScrollArrangement',
    version: '2',
    category: 'layout',
    icon: '⬍',
    defaultName: 'VerticalScrollArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
    },
    events: [],
    methods: {},
  },

  TableArrangement: {
    type: 'TableArrangement',
    version: '1',
    category: 'layout',
    icon: '⊞',
    defaultName: 'TableArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Columns: { type: 'number', default: '2' },
      Rows: { type: 'number', default: '2' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {},
  },

  // ==========================================================================
  // MEDIA
  // ==========================================================================

  Camera: {
    type: 'Camera',
    version: '3',
    category: 'media',
    icon: '📷',
    defaultName: 'Camera',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: ['AfterPicture'],
    methods: {
      TakePicture: { params: [] },
    },
  },

  Player: {
    type: 'Player',
    version: '7',
    category: 'media',
    icon: '▶️',
    defaultName: 'Player',
    isVisible: false,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      Volume: { type: 'number', default: '50' },
      Loop: { type: 'boolean', default: 'False' },
      PlayOnlyInForeground: { type: 'boolean', default: 'False' },
      IsPlaying: { type: 'boolean', default: 'False' },
    },
    events: ['Completed', 'PlayerError'],
    methods: {
      Start: { params: [] },
      Pause: { params: [] },
      Stop: { params: [] },
    },
  },

  Sound: {
    type: 'Sound',
    version: '4',
    category: 'media',
    icon: '🔊',
    defaultName: 'Sound',
    isVisible: false,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      MinimumInterval: { type: 'number', default: '500' },
    },
    events: [],
    methods: {
      Play: { params: [] },
      Pause: { params: [] },
      Resume: { params: [] },
      Stop: { params: [] },
      Vibrate: { params: ['milliseconds'] },
    },
  },

  SpeechRecognizer: {
    type: 'SpeechRecognizer',
    version: '3',
    category: 'media',
    icon: '🎤',
    defaultName: 'SpeechRecognizer',
    isVisible: false,
    isLayout: false,
    properties: {
      Language: { type: 'string', default: '' },
      UseLegacy: { type: 'boolean', default: 'True' },
    },
    events: ['BeforeGettingText', 'AfterGettingText'],
    methods: {
      GetText: { params: [] },
      Stop: { params: [] },
    },
  },

  TextToSpeech: {
    type: 'TextToSpeech',
    version: '6',
    category: 'media',
    icon: '🗣️',
    defaultName: 'TextToSpeech',
    isVisible: false,
    isLayout: false,
    properties: {
      Language: { type: 'string', default: '' },
      Country: { type: 'string', default: '' },
      Pitch: { type: 'number', default: '1.0' },
      SpeechRate: { type: 'number', default: '1.0' },
    },
    events: ['BeforeSpeaking', 'AfterSpeaking'],
    methods: {
      Speak: { params: ['message'] },
    },
  },

  VideoPlayer: {
    type: 'VideoPlayer',
    version: '7',
    category: 'media',
    icon: '🎬',
    defaultName: 'VideoPlayer',
    isVisible: true,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      Volume: { type: 'number', default: '50' },
      FullScreen: { type: 'boolean', default: 'False' },
    },
    events: ['Completed'],
    methods: {
      Start: { params: [] },
      Pause: { params: [] },
      Stop: { params: [] },
      SeekTo: { params: ['ms'] },
      GetDuration: { params: [] },
    },
  },

  // ==========================================================================
  // DRAWING & ANIMATION
  // ==========================================================================

  Canvas: {
    type: 'Canvas',
    version: '15',
    category: 'drawing',
    icon: '🎨',
    defaultName: 'Canvas',
    isVisible: true,
    isLayout: false,
    properties: {
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '200' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      BackgroundImage: { type: 'asset', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      PaintColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      LineWidth: { type: 'number', default: '2.0' },
      TextAlignment: { type: 'number', default: '1' },
    },
    events: ['Touched', 'Dragged', 'TouchDown', 'TouchUp', 'Flung'],
    methods: {
      Clear: { params: [] },
      DrawPoint: { params: ['x', 'y'] },
      DrawLine: { params: ['x1', 'y1', 'x2', 'y2'] },
      DrawCircle: { params: ['centerX', 'centerY', 'radius', 'fill'] },
      DrawText: { params: ['text', 'x', 'y'] },
      DrawTextAtAngle: { params: ['text', 'x', 'y', 'angle'] },
      Save: { params: [] },
      SaveAs: { params: ['fileName'] },
    },
  },

  Ball: {
    type: 'Ball',
    version: '8',
    category: 'drawing',
    icon: '⚽',
    defaultName: 'Ball',
    isVisible: true,
    isLayout: false,
    properties: {
      X: { type: 'number', default: '0' },
      Y: { type: 'number', default: '0' },
      Radius: { type: 'number', default: '5' },
      PaintColor: { type: 'color', default: '&HFF000000' },
      Speed: { type: 'number', default: '0.0' },
      Heading: { type: 'number', default: '0' },
      Interval: { type: 'number', default: '100' },
      Enabled: { type: 'boolean', default: 'True' },
      Visible: { type: 'boolean', default: 'True' },
      Z: { type: 'number', default: '1.0' },
    },
    events: [
      'CollidedWith', 'EdgeReached', 'Dragged', 'Flung',
      'NoLongerCollidingWith', 'Touched', 'TouchDown', 'TouchUp',
    ],
    methods: {
      Bounce: { params: ['edge'] },
      MoveIntoBounds: { params: [] },
      MoveTo: { params: ['x', 'y'] },
      PointInDirection: { params: ['x', 'y'] },
      PointTowards: { params: ['target'] },
    },
  },

  ImageSprite: {
    type: 'ImageSprite',
    version: '10',
    category: 'drawing',
    icon: '🖼️',
    defaultName: 'ImageSprite',
    isVisible: true,
    isLayout: false,
    properties: {
      Picture: { type: 'asset', default: '' },
      X: { type: 'number', default: '0' },
      Y: { type: 'number', default: '0' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Speed: { type: 'number', default: '0.0' },
      Heading: { type: 'number', default: '0' },
      Interval: { type: 'number', default: '100' },
      Enabled: { type: 'boolean', default: 'True' },
      Visible: { type: 'boolean', default: 'True' },
      Rotates: { type: 'boolean', default: 'True' },
      Z: { type: 'number', default: '1.0' },
    },
    events: [
      'CollidedWith', 'EdgeReached', 'Dragged', 'Flung',
      'NoLongerCollidingWith', 'Touched', 'TouchDown', 'TouchUp',
    ],
    methods: {
      Bounce: { params: ['edge'] },
      MoveIntoBounds: { params: [] },
      MoveTo: { params: ['x', 'y'] },
      PointInDirection: { params: ['x', 'y'] },
      PointTowards: { params: ['target'] },
    },
  },

  // ==========================================================================
  // SENSORS
  // ==========================================================================

  AccelerometerSensor: {
    type: 'AccelerometerSensor',
    version: '5',
    category: 'sensors',
    icon: '📳',
    defaultName: 'AccelerometerSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      MinimumInterval: { type: 'number', default: '400' },
      Sensitivity: { type: 'number', default: '2' },
      Enabled: { type: 'boolean', default: 'True' },
    },
    events: ['AccelerationChanged', 'Shaking'],
    methods: {},
  },

  Clock: {
    type: 'Clock',
    version: '4',
    category: 'sensors',
    icon: '🕐',
    defaultName: 'Clock',
    isVisible: false,
    isLayout: false,
    properties: {
      TimerInterval: { type: 'number', default: '1000' },
      TimerEnabled: { type: 'boolean', default: 'True' },
      TimerAlwaysFires: { type: 'boolean', default: 'True' },
    },
    events: ['Timer'],
    methods: {
      Now: { params: [] },
      SystemTime: { params: [] },
      MakeInstant: { params: ['from'] },
      MakeInstantFromMillis: { params: ['millis'] },
      GetMillis: { params: ['instant'] },
      Duration: { params: ['start', 'end'] },
      DurationToDays: { params: ['duration'] },
      DurationToHours: { params: ['duration'] },
      DurationToMinutes: { params: ['duration'] },
      DurationToSeconds: { params: ['duration'] },
      DurationToWeeks: { params: ['duration'] },
      AddYears: { params: ['instant', 'quantity'] },
      AddMonths: { params: ['instant', 'quantity'] },
      AddWeeks: { params: ['instant', 'quantity'] },
      AddDays: { params: ['instant', 'quantity'] },
      AddHours: { params: ['instant', 'quantity'] },
      AddMinutes: { params: ['instant', 'quantity'] },
      AddSeconds: { params: ['instant', 'quantity'] },
      AddDuration: { params: ['instant', 'quantity'] },
      Year: { params: ['instant'] },
      Month: { params: ['instant'] },
      MonthName: { params: ['instant'] },
      DayOfMonth: { params: ['instant'] },
      Weekday: { params: ['instant'] },
      WeekdayName: { params: ['instant'] },
      Hour: { params: ['instant'] },
      Minute: { params: ['instant'] },
      Second: { params: ['instant'] },
      FormatDateTime: { params: ['instant', 'pattern'] },
      FormatDate: { params: ['instant', 'pattern'] },
      FormatTime: { params: ['instant'] },
    },
  },

  LocationSensor: {
    type: 'LocationSensor',
    version: '4',
    category: 'sensors',
    icon: '📍',
    defaultName: 'LocationSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      TimeInterval: { type: 'number', default: '60000' },
      DistanceInterval: { type: 'number', default: '5' },
      Enabled: { type: 'boolean', default: 'True' },
      ProviderName: { type: 'string', default: '' },
      ProviderLocked: { type: 'boolean', default: 'True' },
    },
    events: ['LocationChanged', 'StatusChanged'],
    methods: {
      LatitudeFromAddress: { params: ['locationName'] },
      LongitudeFromAddress: { params: ['locationName'] },
    },
  },

  OrientationSensor: {
    type: 'OrientationSensor',
    version: '2',
    category: 'sensors',
    icon: '🧭',
    defaultName: 'OrientationSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Enabled: { type: 'boolean', default: 'True' },
    },
    events: ['OrientationChanged'],
    methods: {},
  },

  BarcodeScanner: {
    type: 'BarcodeScanner',
    version: '2',
    category: 'sensors',
    icon: '📊',
    defaultName: 'BarcodeScanner',
    isVisible: false,
    isLayout: false,
    properties: {
      UseExternalScanner: { type: 'boolean', default: 'True' },
    },
    events: ['AfterScan'],
    methods: {
      DoScan: { params: [] },
    },
  },

  Pedometer: {
    type: 'Pedometer',
    version: '3',
    category: 'sensors',
    icon: '🚶',
    defaultName: 'Pedometer',
    isVisible: false,
    isLayout: false,
    properties: {
      StopDetectionTimeout: { type: 'number', default: '2000' },
      StrideLength: { type: 'number', default: '0.73' },
    },
    events: ['SimpleStep', 'WalkStep'],
    methods: {
      Start: { params: [] },
      Stop: { params: [] },
      Reset: { params: [] },
      Save: { params: [] },
    },
  },

  ProximitySensor: {
    type: 'ProximitySensor',
    version: '1',
    category: 'sensors',
    icon: '📏',
    defaultName: 'ProximitySensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Enabled: { type: 'boolean', default: 'True' },
      KeepRunningWhenOnPause: { type: 'boolean', default: 'False' },
    },
    events: ['ProximityChanged'],
    methods: {},
  },

  // ==========================================================================
  // SOCIAL
  // ==========================================================================

  PhoneCall: {
    type: 'PhoneCall',
    version: '3',
    category: 'social',
    icon: '📞',
    defaultName: 'PhoneCall',
    isVisible: false,
    isLayout: false,
    properties: {
      PhoneNumber: { type: 'string', default: '' },
    },
    events: ['PhoneCallStarted', 'PhoneCallEnded', 'IncomingCallAnswered'],
    methods: {
      MakePhoneCall: { params: [] },
      MakePhoneCallDirect: { params: [] },
    },
  },

  Texting: {
    type: 'Texting',
    version: '5',
    category: 'social',
    icon: '💬',
    defaultName: 'Texting',
    isVisible: false,
    isLayout: false,
    properties: {
      PhoneNumber: { type: 'string', default: '' },
      Message: { type: 'string', default: '' },
      GoogleVoiceEnabled: { type: 'boolean', default: 'False' },
      ReceivingEnabled: { type: 'number', default: '2' },
    },
    events: ['MessageReceived'],
    methods: {
      SendMessage: { params: [] },
      SendMessageDirect: { params: [] },
    },
  },

  Sharing: {
    type: 'Sharing',
    version: '1',
    category: 'social',
    icon: '🔗',
    defaultName: 'Sharing',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: [],
    methods: {
      ShareMessage: { params: ['message'] },
      ShareFile: { params: ['file'] },
      ShareFileWithMessage: { params: ['file', 'message'] },
    },
  },

  ContactPicker: {
    type: 'ContactPicker',
    version: '6',
    category: 'social',
    icon: '👤',
    defaultName: 'ContactPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'ContactPicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['BeforePicking', 'AfterPicking', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  // ==========================================================================
  // STORAGE
  // ==========================================================================

  TinyDB: {
    type: 'TinyDB',
    version: '3',
    category: 'storage',
    icon: '🗄️',
    defaultName: 'TinyDB',
    isVisible: false,
    isLayout: false,
    properties: {
      Namespace: { type: 'string', default: 'TinyDB1' },
    },
    events: [],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag', 'valueIfTagNotThere'] },
      GetTags: { params: [] },
      ClearAll: { params: [] },
      ClearTag: { params: ['tag'] },
    },
  },

  TinyWebDB: {
    type: 'TinyWebDB',
    version: '2',
    category: 'storage',
    icon: '🌐',
    defaultName: 'TinyWebDB',
    isVisible: false,
    isLayout: false,
    properties: {
      ServiceURL: { type: 'string', default: 'http://tinywebdb.appinventor.mit.edu' },
    },
    events: ['ValueStored', 'GotValue', 'WebServiceError'],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag'] },
    },
  },

  File: {
    type: 'File',
    version: '4',
    category: 'storage',
    icon: '📁',
    defaultName: 'File',
    isVisible: false,
    isLayout: false,
    properties: {
      DefaultScope: { type: 'string', default: 'App' },
    },
    events: ['GotText', 'AfterFileSaved'],
    methods: {
      ReadFrom: { params: ['fileName'] },
      SaveFile: { params: ['text', 'fileName'] },
      AppendToFile: { params: ['text', 'fileName'] },
      Delete: { params: ['fileName'] },
      Exists: { params: ['scope', 'path'] },
      MakeDirectory: { params: ['scope', 'dirName'] },
      ListDirectory: { params: ['scope', 'dirName'] },
      MakeFullPath: { params: ['scope', 'path'] },
      IsDirectory: { params: ['scope', 'path'] },
      CopyFile: { params: ['scope', 'inputPath', 'outputPath'] },
      MoveFile: { params: ['scope', 'inputPath', 'outputPath'] },
      RemoveDirectory: { params: ['scope', 'dirName', 'recursive'] },
    },
  },

  CloudDB: {
    type: 'CloudDB',
    version: '2',
    category: 'storage',
    icon: '☁️',
    defaultName: 'CloudDB',
    isVisible: false,
    isLayout: false,
    properties: {
      ProjectID: { type: 'string', default: '' },
      RedisServer: { type: 'string', default: 'DEFAULT' },
      Token: { type: 'string', default: '' },
      DefaultRedisServer: { type: 'string', default: '' },
      UseSSL: { type: 'boolean', default: 'True' },
    },
    events: ['DataChanged', 'FirstRemoved', 'GotValue', 'UpdateDone'],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag', 'valueIfTagNotThere'] },
      RemoveFirstFromList: { params: ['tag'] },
      AppendValueToList: { params: ['tag', 'itemToAdd'] },
      ClearTag: { params: ['tag'] },
      GetTagList: { params: [] },
      CloudConnected: { params: [] },
    },
  },

  // ==========================================================================
  // CONNECTIVITY
  // ==========================================================================

  Web: {
    type: 'Web',
    version: '9',
    category: 'connectivity',
    icon: '🌐',
    defaultName: 'Web',
    isVisible: false,
    isLayout: false,
    properties: {
      Url: { type: 'string', default: '' },
      RequestHeaders: { type: 'list', default: '' },
      AllowCookies: { type: 'boolean', default: 'False' },
      SaveResponse: { type: 'boolean', default: 'False' },
      ResponseFileName: { type: 'string', default: '' },
      Timeout: { type: 'number', default: '0' },
    },
    events: ['GotText', 'GotFile', 'TimedOut'],
    methods: {
      Get: { params: [] },
      PostText: { params: ['text'] },
      PostTextWithEncoding: { params: ['text', 'encoding'] },
      PostFile: { params: ['path'] },
      PutText: { params: ['text'] },
      PutTextWithEncoding: { params: ['text', 'encoding'] },
      PutFile: { params: ['path'] },
      PatchText: { params: ['text'] },
      PatchTextWithEncoding: { params: ['text', 'encoding'] },
      Delete: { params: [] },
      BuildRequestData: { params: ['list'] },
      UriEncode: { params: ['text'] },
      UriDecode: { params: ['text'] },
      JsonObjectEncode: { params: ['jsonObject'] },
      JsonTextDecode: { params: ['jsonText'] },
      JsonTextDecodeWithDictionaries: { params: ['jsonText'] },
      XmlTextDecode: { params: ['xmlText'] },
      XmlTextDecodeAsDictionary: { params: ['xmlText'] },
      HtmlTextDecode: { params: ['htmlText'] },
    },
  },

  ActivityStarter: {
    type: 'ActivityStarter',
    version: '6',
    category: 'connectivity',
    icon: '🚀',
    defaultName: 'ActivityStarter',
    isVisible: false,
    isLayout: false,
    properties: {
      Action: { type: 'string', default: '' },
      ActivityClass: { type: 'string', default: '' },
      ActivityPackage: { type: 'string', default: '' },
      DataUri: { type: 'string', default: '' },
      DataType: { type: 'string', default: '' },
      ExtraKey: { type: 'string', default: '' },
      ExtraValue: { type: 'string', default: '' },
      Extras: { type: 'list', default: '' },
      ResultName: { type: 'string', default: '' },
      ResultType: { type: 'string', default: '' },
      ResultUri: { type: 'string', default: '' },
    },
    events: ['AfterActivity', 'ActivityCanceled'],
    methods: {
      StartActivity: { params: [] },
      ResolveActivity: { params: [] },
    },
  },

  BluetoothClient: {
    type: 'BluetoothClient',
    version: '8',
    category: 'connectivity',
    icon: '🔵',
    defaultName: 'BluetoothClient',
    isVisible: false,
    isLayout: false,
    properties: {
      AddressesAndNames: { type: 'list', default: '' },
      CharacterEncoding: { type: 'string', default: 'UTF-8' },
      DelimiterByte: { type: 'number', default: '0' },
      HighByteFirst: { type: 'boolean', default: 'False' },
      Secure: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {
      Connect: { params: ['address'] },
      ConnectWithUUID: { params: ['address', 'uuid'] },
      Disconnect: { params: [] },
      IsDevicePaired: { params: ['address'] },
      Send1ByteNumber: { params: ['number'] },
      Send2ByteNumber: { params: ['number'] },
      Send4ByteNumber: { params: ['number'] },
      SendBytes: { params: ['list'] },
      SendText: { params: ['text'] },
      ReceiveSigned1ByteNumber: { params: [] },
      ReceiveUnsigned1ByteNumber: { params: [] },
      ReceiveSigned2ByteNumber: { params: [] },
      ReceiveUnsigned2ByteNumber: { params: [] },
      ReceiveSigned4ByteNumber: { params: [] },
      ReceiveUnsigned4ByteNumber: { params: [] },
      ReceiveSignedBytes: { params: ['numberOfBytes'] },
      ReceiveUnsignedBytes: { params: ['numberOfBytes'] },
      ReceiveText: { params: ['numberOfBytes'] },
      BytesAvailableToReceive: { params: [] },
      IsConnected: { params: [] },
    },
  },

  BluetoothServer: {
    type: 'BluetoothServer',
    version: '5',
    category: 'connectivity',
    icon: '🔷',
    defaultName: 'BluetoothServer',
    isVisible: false,
    isLayout: false,
    properties: {
      CharacterEncoding: { type: 'string', default: 'UTF-8' },
      DelimiterByte: { type: 'number', default: '0' },
      HighByteFirst: { type: 'boolean', default: 'False' },
      Secure: { type: 'boolean', default: 'True' },
    },
    events: ['ConnectionAccepted'],
    methods: {
      AcceptConnection: { params: ['serviceName'] },
      AcceptConnectionWithUUID: { params: ['serviceName', 'uuid'] },
      StopAccepting: { params: [] },
      Disconnect: { params: [] },
      Send1ByteNumber: { params: ['number'] },
      Send2ByteNumber: { params: ['number'] },
      Send4ByteNumber: { params: ['number'] },
      SendBytes: { params: ['list'] },
      SendText: { params: ['text'] },
      ReceiveSigned1ByteNumber: { params: [] },
      ReceiveUnsigned1ByteNumber: { params: [] },
      ReceiveSigned2ByteNumber: { params: [] },
      ReceiveUnsigned2ByteNumber: { params: [] },
      ReceiveSigned4ByteNumber: { params: [] },
      ReceiveUnsigned4ByteNumber: { params: [] },
      ReceiveSignedBytes: { params: ['numberOfBytes'] },
      ReceiveUnsignedBytes: { params: ['numberOfBytes'] },
      ReceiveText: { params: ['numberOfBytes'] },
      BytesAvailableToReceive: { params: [] },
      IsConnected: { params: [] },
    },
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Returns an object of default property values for the given component type.
 * Only includes properties that have a non-empty default value.
 */
export function getDefaultProperties(componentType) {
  const def = COMPONENTS[componentType];
  if (!def) return {};
  const props = {};
  for (const [key, val] of Object.entries(def.properties)) {
    if (val.default !== undefined && val.default !== '') {
      props[key] = val.default;
    }
  }
  return props;
}

/**
 * Generates a unique ID string in the format used by App Inventor components.
 */
export function generateUuid() {
  return '-' + Math.floor(Math.random() * 1000000000);
}
