// Component categories and definitions for MIT App Inventor
// Each component has: type, version, category, icon (emoji), properties, events, methods
// Used by the visual designer and AIA generator.

export const CATEGORIES = [
  { id: 'ui', name: 'User Interface', icon: '🖥️' },
  { id: 'layout', name: 'Layout', icon: '📐' },
  { id: 'media', name: 'Media', icon: '🎵' },
  { id: 'drawing', name: 'Drawing & Animation', icon: '🎨' },
  { id: 'sensors', name: 'Sensors', icon: '📡' },
  { id: 'social', name: 'Social', icon: '📱' },
  { id: 'storage', name: 'Storage', icon: '💾' },
  { id: 'connectivity', name: 'Connectivity', icon: '🌐' },
  { id: 'maps', name: 'Maps', icon: '🗺️' },
  { id: 'charts', name: 'Charts', icon: '📊' },
  { id: 'datascience', name: 'Data Science', icon: '🔬' },
  { id: 'lego', name: 'LEGO MINDSTORMS', icon: '🤖' },
  { id: 'experimental', name: 'Experimental', icon: '🧪' },
];

export const COMPONENTS = {

  // ==========================================================================
  // USER INTERFACE
  // ==========================================================================

  Button: {
    type: 'Button',
    version: '7',
    category: 'ui',
    icon: '🔘',
    defaultName: 'Button',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Button' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Shape: { type: 'number', default: '0' },
      Image: { type: 'asset', default: '' },
      TextAlignment: { type: 'number', default: '1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Click', 'GotFocus', 'LostFocus', 'LongClick', 'TouchDown', 'TouchUp'],
    methods: {},
  },

  Label: {
    type: 'Label',
    version: '5',
    category: 'ui',
    icon: '🏷️',
    defaultName: 'Label',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Label' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      TextAlignment: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
      HTMLFormat: { type: 'boolean', default: 'False' },
      HasMargins: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {},
  },

  TextBox: {
    type: 'TextBox',
    version: '14',
    category: 'ui',
    icon: '📝',
    defaultName: 'TextBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: '' },
      Hint: { type: 'string', default: '' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      MultiLine: { type: 'boolean', default: 'False' },
      NumbersOnly: { type: 'boolean', default: 'False' },
      ReadOnly: { type: 'boolean', default: 'False' },
      TextAlignment: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['GotFocus', 'LostFocus'],
    methods: {},
  },

  CheckBox: {
    type: 'CheckBox',
    version: '2',
    category: 'ui',
    icon: '☑️',
    defaultName: 'CheckBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'CheckBox' },
      Checked: { type: 'boolean', default: 'False' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Changed', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  Image: {
    type: 'Image',
    version: '6',
    category: 'ui',
    icon: '🖼️',
    defaultName: 'Image',
    isVisible: true,
    isLayout: false,
    properties: {
      Picture: { type: 'asset', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      ScalePictureToFit: { type: 'boolean', default: 'False' },
      Visible: { type: 'boolean', default: 'True' },
      ClickableImageBase: { type: 'boolean', default: 'False' },
      Rotation: { type: 'number', default: '0.0' },
      Animation: { type: 'string', default: '' },
    },
    events: ['Click'],
    methods: {},
  },

  ListPicker: {
    type: 'ListPicker',
    version: '9',
    category: 'ui',
    icon: '📋',
    defaultName: 'ListPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Title: { type: 'string', default: '' },
      Text: { type: 'string', default: 'ListPicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      ItemBackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      ItemTextColor: { type: 'color', default: '&HFF000000' },
      ShowFilterBar: { type: 'boolean', default: 'False' },
    },
    events: ['BeforePicking', 'AfterPicking', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  ListView: {
    type: 'ListView',
    version: '10',
    category: 'ui',
    icon: '📃',
    defaultName: 'ListView',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&HFF000000' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      TextSize: { type: 'number', default: '22' },
      SelectionColor: { type: 'color', default: '&HFFCCCCCC' },
      ShowFilterBar: { type: 'boolean', default: 'False' },
    },
    events: ['AfterPicking'],
    methods: {},
  },

  Notifier: {
    type: 'Notifier',
    version: '6',
    category: 'ui',
    icon: '🔔',
    defaultName: 'Notifier',
    isVisible: false,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFF444444' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      NotifierLength: { type: 'number', default: '1' },
    },
    events: ['AfterChoosing', 'AfterTextInput', 'ChoosingCancelled', 'TextInputCancelled'],
    methods: {
      ShowAlert: { params: ['notice'] },
      ShowChooseDialog: { params: ['message', 'title', 'button1Text', 'button2Text', 'cancelable'] },
      ShowTextDialog: { params: ['message', 'title', 'cancelable'] },
      ShowMessageDialog: { params: ['message', 'title', 'buttonText'] },
      ShowProgressDialog: { params: ['message', 'title'] },
      DismissProgressDialog: { params: [] },
      LogError: { params: ['message'] },
      LogInfo: { params: ['message'] },
      LogWarning: { params: ['message'] },
    },
  },

  Slider: {
    type: 'Slider',
    version: '3',
    category: 'ui',
    icon: '🎚️',
    defaultName: 'Slider',
    isVisible: true,
    isLayout: false,
    properties: {
      MinValue: { type: 'number', default: '10' },
      MaxValue: { type: 'number', default: '50' },
      ThumbPosition: { type: 'number', default: '30' },
      Width: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      ColorLeft: { type: 'color', default: '&HFFFF6600' },
      ColorRight: { type: 'color', default: '&HFF888888' },
      ThumbEnabled: { type: 'boolean', default: 'True' },
    },
    events: ['PositionChanged'],
    methods: {},
  },

  Spinner: {
    type: 'Spinner',
    version: '2',
    category: 'ui',
    icon: '🔽',
    defaultName: 'Spinner',
    isVisible: true,
    isLayout: false,
    properties: {
      Elements: { type: 'list', default: '' },
      ElementsFromString: { type: 'string', default: '' },
      Selection: { type: 'string', default: '' },
      SelectionIndex: { type: 'number', default: '0' },
      Prompt: { type: 'string', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['AfterSelecting'],
    methods: {},
  },

  Switch: {
    type: 'Switch',
    version: '1',
    category: 'ui',
    icon: '🔀',
    defaultName: 'Switch',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'Switch' },
      On: { type: 'boolean', default: 'False' },
      Checked: { type: 'boolean', default: 'False' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      ThumbColorActive: { type: 'color', default: '&HFFFFFFFF' },
      ThumbColorInactive: { type: 'color', default: '&HFFCCCCCC' },
      TrackColorActive: { type: 'color', default: '&HFF00BCD4' },
      TrackColorInactive: { type: 'color', default: '&HFF9E9E9E' },
    },
    events: ['Changed'],
    methods: {},
  },

  DatePicker: {
    type: 'DatePicker',
    version: '4',
    category: 'ui',
    icon: '📅',
    defaultName: 'DatePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'DatePicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['DateSet', 'GotFocus', 'LostFocus'],
    methods: {
      SetDateToDisplay: { params: ['year', 'month', 'day'] },
      LaunchPicker: { params: [] },
    },
  },

  TimePicker: {
    type: 'TimePicker',
    version: '4',
    category: 'ui',
    icon: '⏰',
    defaultName: 'TimePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'TimePicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['TimeSet', 'GotFocus', 'LostFocus'],
    methods: {
      SetTimeToDisplay: { params: ['hour', 'minute'] },
      LaunchPicker: { params: [] },
    },
  },

  PasswordTextBox: {
    type: 'PasswordTextBox',
    version: '7',
    category: 'ui',
    icon: '🔒',
    defaultName: 'PasswordTextBox',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: '' },
      Hint: { type: 'string', default: '' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      TextColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      NumbersOnly: { type: 'boolean', default: 'False' },
    },
    events: ['GotFocus', 'LostFocus'],
    methods: {},
  },

  WebViewer: {
    type: 'WebViewer',
    version: '11',
    category: 'ui',
    icon: '🌍',
    defaultName: 'WebViewer',
    isVisible: true,
    isLayout: false,
    properties: {
      HomeUrl: { type: 'string', default: '' },
      CurrentUrl: { type: 'string', default: '' },
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '-2' },
      Visible: { type: 'boolean', default: 'True' },
      FollowLinks: { type: 'boolean', default: 'True' },
      IgnoreSslErrors: { type: 'boolean', default: 'False' },
      UsesLocation: { type: 'boolean', default: 'False' },
    },
    events: ['WebViewStringChange', 'PageLoaded', 'BeforePageLoad', 'ErrorOccurred'],
    methods: {
      GoBack: { params: [] },
      GoForward: { params: [] },
      GoHome: { params: [] },
      GoToUrl: { params: ['url'] },
      CanGoBack: { params: [] },
      CanGoForward: { params: [] },
      ClearCaches: { params: [] },
      Reload: { params: [] },
    },
  },

  CircularProgress: {
    type: 'CircularProgress',
    version: '1',
    category: 'ui',
    icon: '⭕',
    defaultName: 'CircularProgress',
    isVisible: true,
    isLayout: false,
    properties: {
      Height: { type: 'length', default: '-1' },
      IndeterminateProgress: { type: 'boolean', default: 'False' },
      Maximum: { type: 'number', default: '100' },
      Progress: { type: 'number', default: '0' },
      ProgressColor: { type: 'color', default: '&HFF0000FF' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: [],
    methods: {},
  },

  LinearProgress: {
    type: 'LinearProgress',
    version: '1',
    category: 'ui',
    icon: '▬',
    defaultName: 'LinearProgress',
    isVisible: true,
    isLayout: false,
    properties: {
      Height: { type: 'length', default: '-1' },
      IndeterminateProgress: { type: 'boolean', default: 'False' },
      Maximum: { type: 'number', default: '100' },
      Progress: { type: 'number', default: '0' },
      ProgressColor: { type: 'color', default: '&HFF0000FF' },
      SecondaryProgress: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-2' },
    },
    events: [],
    methods: {},
  },

  // ==========================================================================
  // LAYOUT
  // ==========================================================================

  HorizontalArrangement: {
    type: 'HorizontalArrangement',
    version: '4',
    category: 'layout',
    icon: '↔️',
    defaultName: 'HorizontalArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
      Image: { type: 'asset', default: '' },
    },
    events: [],
    methods: {},
  },

  VerticalArrangement: {
    type: 'VerticalArrangement',
    version: '4',
    category: 'layout',
    icon: '↕️',
    defaultName: 'VerticalArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
      Image: { type: 'asset', default: '' },
    },
    events: [],
    methods: {},
  },

  HorizontalScrollArrangement: {
    type: 'HorizontalScrollArrangement',
    version: '2',
    category: 'layout',
    icon: '⬌',
    defaultName: 'HorizontalScrollArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
    },
    events: [],
    methods: {},
  },

  VerticalScrollArrangement: {
    type: 'VerticalScrollArrangement',
    version: '2',
    category: 'layout',
    icon: '⬍',
    defaultName: 'VerticalScrollArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      AlignHorizontal: { type: 'number', default: '1' },
      AlignVertical: { type: 'number', default: '1' },
    },
    events: [],
    methods: {},
  },

  TableArrangement: {
    type: 'TableArrangement',
    version: '1',
    category: 'layout',
    icon: '⊞',
    defaultName: 'TableArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      Columns: { type: 'number', default: '2' },
      Rows: { type: 'number', default: '2' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {},
  },

  AbsoluteArrangement: {
    type: 'AbsoluteArrangement',
    version: '1',
    category: 'layout',
    icon: '📌',
    defaultName: 'AbsoluteArrangement',
    isVisible: true,
    isLayout: true,
    properties: {
      BackgroundColor: { type: 'color', default: '&H00FFFFFF' },
      Height: { type: 'length', default: '-1' },
      Image: { type: 'asset', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: [],
    methods: {},
  },

  // ==========================================================================
  // MEDIA
  // ==========================================================================

  Camera: {
    type: 'Camera',
    version: '3',
    category: 'media',
    icon: '📷',
    defaultName: 'Camera',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: ['AfterPicture'],
    methods: {
      TakePicture: { params: [] },
    },
  },

  Player: {
    type: 'Player',
    version: '7',
    category: 'media',
    icon: '▶️',
    defaultName: 'Player',
    isVisible: false,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      Volume: { type: 'number', default: '50' },
      Loop: { type: 'boolean', default: 'False' },
      PlayOnlyInForeground: { type: 'boolean', default: 'False' },
      IsPlaying: { type: 'boolean', default: 'False' },
    },
    events: ['Completed', 'PlayerError'],
    methods: {
      Start: { params: [] },
      Pause: { params: [] },
      Stop: { params: [] },
    },
  },

  Sound: {
    type: 'Sound',
    version: '4',
    category: 'media',
    icon: '🔊',
    defaultName: 'Sound',
    isVisible: false,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      MinimumInterval: { type: 'number', default: '500' },
    },
    events: [],
    methods: {
      Play: { params: [] },
      Pause: { params: [] },
      Resume: { params: [] },
      Stop: { params: [] },
      Vibrate: { params: ['milliseconds'] },
    },
  },

  SpeechRecognizer: {
    type: 'SpeechRecognizer',
    version: '3',
    category: 'media',
    icon: '🎤',
    defaultName: 'SpeechRecognizer',
    isVisible: false,
    isLayout: false,
    properties: {
      Language: { type: 'string', default: '' },
      UseLegacy: { type: 'boolean', default: 'True' },
    },
    events: ['BeforeGettingText', 'AfterGettingText'],
    methods: {
      GetText: { params: [] },
      Stop: { params: [] },
    },
  },

  TextToSpeech: {
    type: 'TextToSpeech',
    version: '6',
    category: 'media',
    icon: '🗣️',
    defaultName: 'TextToSpeech',
    isVisible: false,
    isLayout: false,
    properties: {
      Language: { type: 'string', default: '' },
      Country: { type: 'string', default: '' },
      Pitch: { type: 'number', default: '1.0' },
      SpeechRate: { type: 'number', default: '1.0' },
    },
    events: ['BeforeSpeaking', 'AfterSpeaking'],
    methods: {
      Speak: { params: ['message'] },
    },
  },

  VideoPlayer: {
    type: 'VideoPlayer',
    version: '7',
    category: 'media',
    icon: '🎬',
    defaultName: 'VideoPlayer',
    isVisible: true,
    isLayout: false,
    properties: {
      Source: { type: 'asset', default: '' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
      Volume: { type: 'number', default: '50' },
      FullScreen: { type: 'boolean', default: 'False' },
    },
    events: ['Completed'],
    methods: {
      Start: { params: [] },
      Pause: { params: [] },
      Stop: { params: [] },
      SeekTo: { params: ['ms'] },
      GetDuration: { params: [] },
    },
  },

  Camcorder: {
    type: 'Camcorder',
    version: '1',
    category: 'media',
    icon: '🎥',
    defaultName: 'Camcorder',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: ['AfterRecording'],
    methods: {
      RecordVideo: { params: [] },
    },
  },

  FilePicker: {
    type: 'FilePicker',
    version: '1',
    category: 'media',
    icon: '📂',
    defaultName: 'FilePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      Enabled: { type: 'boolean', default: 'True' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      FontSize: { type: 'number', default: '14.0' },
      FontTypeface: { type: 'number', default: '0' },
      Height: { type: 'length', default: '-1' },
      Image: { type: 'asset', default: '' },
      MimeType: { type: 'string', default: '*/*' },
      Selection: { type: 'string', default: '' },
      Shape: { type: 'number', default: '0' },
      ShowFeedback: { type: 'boolean', default: 'True' },
      Text: { type: 'string', default: 'Choose File' },
      TextAlignment: { type: 'number', default: '1' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['AfterPicking', 'BeforePicking', 'GotFocus', 'LostFocus', 'TouchDown', 'TouchUp'],
    methods: {
      Open: { params: [] },
    },
  },

  ImagePicker: {
    type: 'ImagePicker',
    version: '5',
    category: 'media',
    icon: '🖼️',
    defaultName: 'ImagePicker',
    isVisible: true,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      Enabled: { type: 'boolean', default: 'True' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      FontSize: { type: 'number', default: '14.0' },
      FontTypeface: { type: 'number', default: '0' },
      Height: { type: 'length', default: '-1' },
      Image: { type: 'asset', default: '' },
      Selection: { type: 'string', default: '' },
      Shape: { type: 'number', default: '0' },
      ShowFeedback: { type: 'boolean', default: 'True' },
      Text: { type: 'string', default: 'Choose Image' },
      TextAlignment: { type: 'number', default: '1' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['AfterPicking', 'BeforePicking', 'GotFocus', 'LostFocus', 'TouchDown', 'TouchUp'],
    methods: {
      Open: { params: [] },
    },
  },

  SoundRecorder: {
    type: 'SoundRecorder',
    version: '2',
    category: 'media',
    icon: '🎙️',
    defaultName: 'SoundRecorder',
    isVisible: false,
    isLayout: false,
    properties: {
      SavedRecording: { type: 'string', default: '' },
    },
    events: ['AfterSoundRecorded', 'StartedRecording', 'StoppedRecording'],
    methods: {
      Start: { params: [] },
      Stop: { params: [] },
    },
  },

  Translator: {
    type: 'Translator',
    version: '1',
    category: 'media',
    icon: '🌍',
    defaultName: 'Translator',
    isVisible: false,
    isLayout: false,
    properties: {
      ApiKey: { type: 'string', default: '' },
    },
    events: ['GotTranslation'],
    methods: {
      RequestTranslation: { params: ['languageToTranslateTo', 'textToTranslate'] },
    },
  },

  // ==========================================================================
  // DRAWING & ANIMATION
  // ==========================================================================

  Canvas: {
    type: 'Canvas',
    version: '15',
    category: 'drawing',
    icon: '🎨',
    defaultName: 'Canvas',
    isVisible: true,
    isLayout: false,
    properties: {
      Width: { type: 'length', default: '-2' },
      Height: { type: 'length', default: '200' },
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      BackgroundImage: { type: 'asset', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      PaintColor: { type: 'color', default: '&HFF000000' },
      FontSize: { type: 'number', default: '14.0' },
      LineWidth: { type: 'number', default: '2.0' },
      TextAlignment: { type: 'number', default: '1' },
    },
    events: ['Touched', 'Dragged', 'TouchDown', 'TouchUp', 'Flung'],
    methods: {
      Clear: { params: [] },
      DrawPoint: { params: ['x', 'y'] },
      DrawLine: { params: ['x1', 'y1', 'x2', 'y2'] },
      DrawCircle: { params: ['centerX', 'centerY', 'radius', 'fill'] },
      DrawText: { params: ['text', 'x', 'y'] },
      DrawTextAtAngle: { params: ['text', 'x', 'y', 'angle'] },
      Save: { params: [] },
      SaveAs: { params: ['fileName'] },
    },
  },

  Ball: {
    type: 'Ball',
    version: '8',
    category: 'drawing',
    icon: '⚽',
    defaultName: 'Ball',
    isVisible: true,
    isLayout: false,
    properties: {
      X: { type: 'number', default: '0' },
      Y: { type: 'number', default: '0' },
      Radius: { type: 'number', default: '5' },
      PaintColor: { type: 'color', default: '&HFF000000' },
      Speed: { type: 'number', default: '0.0' },
      Heading: { type: 'number', default: '0' },
      Interval: { type: 'number', default: '100' },
      Enabled: { type: 'boolean', default: 'True' },
      Visible: { type: 'boolean', default: 'True' },
      Z: { type: 'number', default: '1.0' },
    },
    events: [
      'CollidedWith', 'EdgeReached', 'Dragged', 'Flung',
      'NoLongerCollidingWith', 'Touched', 'TouchDown', 'TouchUp',
    ],
    methods: {
      Bounce: { params: ['edge'] },
      MoveIntoBounds: { params: [] },
      MoveTo: { params: ['x', 'y'] },
      PointInDirection: { params: ['x', 'y'] },
      PointTowards: { params: ['target'] },
    },
  },

  ImageSprite: {
    type: 'ImageSprite',
    version: '10',
    category: 'drawing',
    icon: '🖼️',
    defaultName: 'ImageSprite',
    isVisible: true,
    isLayout: false,
    properties: {
      Picture: { type: 'asset', default: '' },
      X: { type: 'number', default: '0' },
      Y: { type: 'number', default: '0' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Speed: { type: 'number', default: '0.0' },
      Heading: { type: 'number', default: '0' },
      Interval: { type: 'number', default: '100' },
      Enabled: { type: 'boolean', default: 'True' },
      Visible: { type: 'boolean', default: 'True' },
      Rotates: { type: 'boolean', default: 'True' },
      Z: { type: 'number', default: '1.0' },
    },
    events: [
      'CollidedWith', 'EdgeReached', 'Dragged', 'Flung',
      'NoLongerCollidingWith', 'Touched', 'TouchDown', 'TouchUp',
    ],
    methods: {
      Bounce: { params: ['edge'] },
      MoveIntoBounds: { params: [] },
      MoveTo: { params: ['x', 'y'] },
      PointInDirection: { params: ['x', 'y'] },
      PointTowards: { params: ['target'] },
    },
  },

  // ==========================================================================
  // SENSORS
  // ==========================================================================

  AccelerometerSensor: {
    type: 'AccelerometerSensor',
    version: '5',
    category: 'sensors',
    icon: '📳',
    defaultName: 'AccelerometerSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      MinimumInterval: { type: 'number', default: '400' },
      Sensitivity: { type: 'number', default: '2' },
      Enabled: { type: 'boolean', default: 'True' },
    },
    events: ['AccelerationChanged', 'Shaking'],
    methods: {},
  },

  Clock: {
    type: 'Clock',
    version: '4',
    category: 'sensors',
    icon: '🕐',
    defaultName: 'Clock',
    isVisible: false,
    isLayout: false,
    properties: {
      TimerInterval: { type: 'number', default: '1000' },
      TimerEnabled: { type: 'boolean', default: 'True' },
      TimerAlwaysFires: { type: 'boolean', default: 'True' },
    },
    events: ['Timer'],
    methods: {
      Now: { params: [] },
      SystemTime: { params: [] },
      MakeInstant: { params: ['from'] },
      MakeInstantFromMillis: { params: ['millis'] },
      GetMillis: { params: ['instant'] },
      Duration: { params: ['start', 'end'] },
      DurationToDays: { params: ['duration'] },
      DurationToHours: { params: ['duration'] },
      DurationToMinutes: { params: ['duration'] },
      DurationToSeconds: { params: ['duration'] },
      DurationToWeeks: { params: ['duration'] },
      AddYears: { params: ['instant', 'quantity'] },
      AddMonths: { params: ['instant', 'quantity'] },
      AddWeeks: { params: ['instant', 'quantity'] },
      AddDays: { params: ['instant', 'quantity'] },
      AddHours: { params: ['instant', 'quantity'] },
      AddMinutes: { params: ['instant', 'quantity'] },
      AddSeconds: { params: ['instant', 'quantity'] },
      AddDuration: { params: ['instant', 'quantity'] },
      Year: { params: ['instant'] },
      Month: { params: ['instant'] },
      MonthName: { params: ['instant'] },
      DayOfMonth: { params: ['instant'] },
      Weekday: { params: ['instant'] },
      WeekdayName: { params: ['instant'] },
      Hour: { params: ['instant'] },
      Minute: { params: ['instant'] },
      Second: { params: ['instant'] },
      FormatDateTime: { params: ['instant', 'pattern'] },
      FormatDate: { params: ['instant', 'pattern'] },
      FormatTime: { params: ['instant'] },
    },
  },

  LocationSensor: {
    type: 'LocationSensor',
    version: '4',
    category: 'sensors',
    icon: '📍',
    defaultName: 'LocationSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      TimeInterval: { type: 'number', default: '60000' },
      DistanceInterval: { type: 'number', default: '5' },
      Enabled: { type: 'boolean', default: 'True' },
      ProviderName: { type: 'string', default: '' },
      ProviderLocked: { type: 'boolean', default: 'True' },
    },
    events: ['LocationChanged', 'StatusChanged'],
    methods: {
      LatitudeFromAddress: { params: ['locationName'] },
      LongitudeFromAddress: { params: ['locationName'] },
    },
  },

  OrientationSensor: {
    type: 'OrientationSensor',
    version: '2',
    category: 'sensors',
    icon: '🧭',
    defaultName: 'OrientationSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Enabled: { type: 'boolean', default: 'True' },
    },
    events: ['OrientationChanged'],
    methods: {},
  },

  BarcodeScanner: {
    type: 'BarcodeScanner',
    version: '2',
    category: 'sensors',
    icon: '📊',
    defaultName: 'BarcodeScanner',
    isVisible: false,
    isLayout: false,
    properties: {
      UseExternalScanner: { type: 'boolean', default: 'True' },
    },
    events: ['AfterScan'],
    methods: {
      DoScan: { params: [] },
    },
  },

  Pedometer: {
    type: 'Pedometer',
    version: '3',
    category: 'sensors',
    icon: '🚶',
    defaultName: 'Pedometer',
    isVisible: false,
    isLayout: false,
    properties: {
      StopDetectionTimeout: { type: 'number', default: '2000' },
      StrideLength: { type: 'number', default: '0.73' },
    },
    events: ['SimpleStep', 'WalkStep'],
    methods: {
      Start: { params: [] },
      Stop: { params: [] },
      Reset: { params: [] },
      Save: { params: [] },
    },
  },

  ProximitySensor: {
    type: 'ProximitySensor',
    version: '1',
    category: 'sensors',
    icon: '📏',
    defaultName: 'ProximitySensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Enabled: { type: 'boolean', default: 'True' },
      KeepRunningWhenOnPause: { type: 'boolean', default: 'False' },
    },
    events: ['ProximityChanged'],
    methods: {},
  },

  Barometer: {
    type: 'Barometer',
    version: '1',
    category: 'sensors',
    icon: '🌡️',
    defaultName: 'Barometer',
    isVisible: false,
    isLayout: false,
    properties: {
      AirPressure: { type: 'number', default: '0' },
      Available: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      RefreshTime: { type: 'number', default: '1000' },
    },
    events: ['AirPressureChanged'],
    methods: {},
  },

  GyroscopeSensor: {
    type: 'GyroscopeSensor',
    version: '1',
    category: 'sensors',
    icon: '🌀',
    defaultName: 'GyroscopeSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Available: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      XAngularVelocity: { type: 'number', default: '0' },
      YAngularVelocity: { type: 'number', default: '0' },
      ZAngularVelocity: { type: 'number', default: '0' },
    },
    events: ['GyroscopeChanged'],
    methods: {},
  },

  Hygrometer: {
    type: 'Hygrometer',
    version: '1',
    category: 'sensors',
    icon: '💧',
    defaultName: 'Hygrometer',
    isVisible: false,
    isLayout: false,
    properties: {
      Available: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      Humidity: { type: 'number', default: '0' },
      RefreshTime: { type: 'number', default: '1000' },
    },
    events: ['HumidityChanged'],
    methods: {},
  },

  LightSensor: {
    type: 'LightSensor',
    version: '1',
    category: 'sensors',
    icon: '☀️',
    defaultName: 'LightSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      Available: { type: 'boolean', default: 'False' },
      AverageLux: { type: 'number', default: '0' },
      Enabled: { type: 'boolean', default: 'True' },
      Lux: { type: 'number', default: '0' },
      RefreshTime: { type: 'number', default: '1000' },
    },
    events: ['LightChanged'],
    methods: {},
  },

  MagneticFieldSensor: {
    type: 'MagneticFieldSensor',
    version: '1',
    category: 'sensors',
    icon: '🧲',
    defaultName: 'MagneticFieldSensor',
    isVisible: false,
    isLayout: false,
    properties: {
      AbsoluteStrength: { type: 'number', default: '0' },
      Available: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      MaximumRange: { type: 'number', default: '0' },
      XStrength: { type: 'number', default: '0' },
      YStrength: { type: 'number', default: '0' },
      ZStrength: { type: 'number', default: '0' },
    },
    events: ['MagneticChanged'],
    methods: {},
  },

  NearField: {
    type: 'NearField',
    version: '1',
    category: 'sensors',
    icon: '📡',
    defaultName: 'NearField',
    isVisible: false,
    isLayout: false,
    properties: {
      LastMessage: { type: 'string', default: '' },
      ReadMode: { type: 'boolean', default: 'True' },
      TextToWrite: { type: 'string', default: '' },
      WriteType: { type: 'number', default: '0' },
    },
    events: ['TagRead', 'TagWritten'],
    methods: {},
  },

  Thermometer: {
    type: 'Thermometer',
    version: '1',
    category: 'sensors',
    icon: '🌡️',
    defaultName: 'Thermometer',
    isVisible: false,
    isLayout: false,
    properties: {
      Available: { type: 'boolean', default: 'False' },
      Enabled: { type: 'boolean', default: 'True' },
      RefreshTime: { type: 'number', default: '1000' },
      Temperature: { type: 'number', default: '0' },
    },
    events: ['TemperatureChanged'],
    methods: {},
  },

  // ==========================================================================
  // SOCIAL
  // ==========================================================================

  PhoneCall: {
    type: 'PhoneCall',
    version: '3',
    category: 'social',
    icon: '📞',
    defaultName: 'PhoneCall',
    isVisible: false,
    isLayout: false,
    properties: {
      PhoneNumber: { type: 'string', default: '' },
    },
    events: ['PhoneCallStarted', 'PhoneCallEnded', 'IncomingCallAnswered'],
    methods: {
      MakePhoneCall: { params: [] },
      MakePhoneCallDirect: { params: [] },
    },
  },

  Texting: {
    type: 'Texting',
    version: '5',
    category: 'social',
    icon: '💬',
    defaultName: 'Texting',
    isVisible: false,
    isLayout: false,
    properties: {
      PhoneNumber: { type: 'string', default: '' },
      Message: { type: 'string', default: '' },
      GoogleVoiceEnabled: { type: 'boolean', default: 'False' },
      ReceivingEnabled: { type: 'number', default: '2' },
    },
    events: ['MessageReceived'],
    methods: {
      SendMessage: { params: [] },
      SendMessageDirect: { params: [] },
    },
  },

  Sharing: {
    type: 'Sharing',
    version: '1',
    category: 'social',
    icon: '🔗',
    defaultName: 'Sharing',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: [],
    methods: {
      ShareMessage: { params: ['message'] },
      ShareFile: { params: ['file'] },
      ShareFileWithMessage: { params: ['file', 'message'] },
    },
  },

  ContactPicker: {
    type: 'ContactPicker',
    version: '6',
    category: 'social',
    icon: '👤',
    defaultName: 'ContactPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      Text: { type: 'string', default: 'ContactPicker' },
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      FontSize: { type: 'number', default: '14.0' },
      FontBold: { type: 'boolean', default: 'False' },
      Width: { type: 'length', default: '-1' },
      Height: { type: 'length', default: '-1' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['BeforePicking', 'AfterPicking', 'GotFocus', 'LostFocus'],
    methods: {},
  },

  EmailPicker: {
    type: 'EmailPicker',
    version: '7',
    category: 'social',
    icon: '📧',
    defaultName: 'EmailPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      Enabled: { type: 'boolean', default: 'True' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      FontSize: { type: 'number', default: '14.0' },
      FontTypeface: { type: 'number', default: '0' },
      Height: { type: 'length', default: '-1' },
      Hint: { type: 'string', default: '' },
      Text: { type: 'string', default: '' },
      TextAlignment: { type: 'number', default: '0' },
      TextColor: { type: 'color', default: '&HFF000000' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['GotFocus', 'LostFocus'],
    methods: {
      RequestFocus: { params: [] },
    },
  },

  PhoneNumberPicker: {
    type: 'PhoneNumberPicker',
    version: '4',
    category: 'social',
    icon: '📱',
    defaultName: 'PhoneNumberPicker',
    isVisible: true,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFF3F51B5' },
      Enabled: { type: 'boolean', default: 'True' },
      FontBold: { type: 'boolean', default: 'False' },
      FontItalic: { type: 'boolean', default: 'False' },
      FontSize: { type: 'number', default: '14.0' },
      FontTypeface: { type: 'number', default: '0' },
      Height: { type: 'length', default: '-1' },
      Image: { type: 'asset', default: '' },
      Shape: { type: 'number', default: '0' },
      ShowFeedback: { type: 'boolean', default: 'True' },
      Text: { type: 'string', default: 'Pick Contact Phone' },
      TextAlignment: { type: 'number', default: '1' },
      TextColor: { type: 'color', default: '&HFFFFFFFF' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['AfterPicking', 'BeforePicking', 'GotFocus', 'LostFocus', 'TouchDown', 'TouchUp'],
    methods: {
      Open: { params: [] },
      ViewContact: { params: ['uri'] },
    },
  },

  // ==========================================================================
  // STORAGE
  // ==========================================================================

  TinyDB: {
    type: 'TinyDB',
    version: '3',
    category: 'storage',
    icon: '🗄️',
    defaultName: 'TinyDB',
    isVisible: false,
    isLayout: false,
    properties: {
      Namespace: { type: 'string', default: 'TinyDB1' },
    },
    events: [],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag', 'valueIfTagNotThere'] },
      GetTags: { params: [] },
      ClearAll: { params: [] },
      ClearTag: { params: ['tag'] },
    },
  },

  TinyWebDB: {
    type: 'TinyWebDB',
    version: '2',
    category: 'storage',
    icon: '🌐',
    defaultName: 'TinyWebDB',
    isVisible: false,
    isLayout: false,
    properties: {
      ServiceURL: { type: 'string', default: 'http://tinywebdb.appinventor.mit.edu' },
    },
    events: ['ValueStored', 'GotValue', 'WebServiceError'],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag'] },
    },
  },

  File: {
    type: 'File',
    version: '4',
    category: 'storage',
    icon: '📁',
    defaultName: 'File',
    isVisible: false,
    isLayout: false,
    properties: {
      DefaultScope: { type: 'string', default: 'App' },
    },
    events: ['GotText', 'AfterFileSaved'],
    methods: {
      ReadFrom: { params: ['fileName'] },
      SaveFile: { params: ['text', 'fileName'] },
      AppendToFile: { params: ['text', 'fileName'] },
      Delete: { params: ['fileName'] },
      Exists: { params: ['scope', 'path'] },
      MakeDirectory: { params: ['scope', 'dirName'] },
      ListDirectory: { params: ['scope', 'dirName'] },
      MakeFullPath: { params: ['scope', 'path'] },
      IsDirectory: { params: ['scope', 'path'] },
      CopyFile: { params: ['scope', 'inputPath', 'outputPath'] },
      MoveFile: { params: ['scope', 'inputPath', 'outputPath'] },
      RemoveDirectory: { params: ['scope', 'dirName', 'recursive'] },
    },
  },

  CloudDB: {
    type: 'CloudDB',
    version: '2',
    category: 'storage',
    icon: '☁️',
    defaultName: 'CloudDB',
    isVisible: false,
    isLayout: false,
    properties: {
      ProjectID: { type: 'string', default: '' },
      RedisServer: { type: 'string', default: 'DEFAULT' },
      Token: { type: 'string', default: '' },
      DefaultRedisServer: { type: 'string', default: '' },
      UseSSL: { type: 'boolean', default: 'True' },
    },
    events: ['DataChanged', 'FirstRemoved', 'GotValue', 'UpdateDone'],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag', 'valueIfTagNotThere'] },
      RemoveFirstFromList: { params: ['tag'] },
      AppendValueToList: { params: ['tag', 'itemToAdd'] },
      ClearTag: { params: ['tag'] },
      GetTagList: { params: [] },
      CloudConnected: { params: [] },
    },
  },

  FirebaseDB: {
    type: 'FirebaseDB',
    version: '3',
    category: 'storage',
    icon: '🔥',
    defaultName: 'FirebaseDB',
    isVisible: false,
    isLayout: false,
    properties: {
      FirebaseToken: { type: 'string', default: '' },
      FirebaseURL: { type: 'string', default: '' },
      ProjectBucket: { type: 'string', default: '' },
      DeveloperBucket: { type: 'string', default: '' },
      Persist: { type: 'boolean', default: 'True' },
    },
    events: ['DataChanged', 'FirebaseError', 'FirstRemoved', 'GotValue', 'TagList'],
    methods: {
      StoreValue: { params: ['tag', 'valueToStore'] },
      GetValue: { params: ['tag', 'valueIfTagNotThere'] },
      AppendValue: { params: ['tag', 'valueToAppend'] },
      RemoveFirst: { params: ['tag'] },
      ClearTag: { params: ['tag'] },
      GetTagList: { params: [] },
      Unauthenticate: { params: [] },
    },
  },

  DataFile: {
    type: 'DataFile',
    version: '1',
    category: 'storage',
    icon: '📄',
    defaultName: 'DataFile',
    isVisible: false,
    isLayout: false,
    properties: {
      ColumnNames: { type: 'list', default: '' },
      Columns: { type: 'list', default: '' },
      DefaultScope: { type: 'string', default: 'App' },
      Rows: { type: 'list', default: '' },
      SourceFile: { type: 'string', default: '' },
    },
    events: [],
    methods: {
      ReadFile: { params: ['fileName'] },
    },
  },

  Spreadsheet: {
    type: 'Spreadsheet',
    version: '4',
    category: 'storage',
    icon: '📊',
    defaultName: 'Spreadsheet',
    isVisible: false,
    isLayout: false,
    properties: {
      ApplicationName: { type: 'string', default: '' },
      CredentialsJson: { type: 'string', default: '' },
      SpreadsheetID: { type: 'string', default: '' },
    },
    events: [
      'ErrorOccurred', 'FinishedAddColumn', 'FinishedAddRow', 'FinishedAddSheet',
      'FinishedClearRange', 'FinishedDeleteSheet', 'FinishedRemoveColumn',
      'FinishedRemoveRow', 'FinishedWriteCell', 'FinishedWriteColumn',
      'FinishedWriteRange', 'FinishedWriteRow', 'GotCellData', 'GotColumnData',
      'GotRangeData', 'GotRowData', 'GotSheetData', 'GotSheetList',
    ],
    methods: {
      AddColumn: { params: ['columnName'] },
      AddRow: { params: ['rowList'] },
      AddSheet: { params: ['sheetName'] },
      ClearRange: { params: ['cellRange'] },
      DeleteSheet: { params: ['sheetName'] },
      GetCellReference: { params: ['column', 'row'] },
      GetRangeReference: { params: ['column1', 'row1', 'column2', 'row2'] },
      ListSheets: { params: [] },
      ReadCell: { params: ['cellReference'] },
      ReadColumn: { params: ['columnNumber'] },
      ReadRange: { params: ['cellRange'] },
      ReadRow: { params: ['rowNumber'] },
      ReadSheet: { params: [] },
      ReadWithExactFilter: { params: ['columnName', 'filterValue'] },
      ReadWithPartialFilter: { params: ['columnName', 'filterValue'] },
      RemoveColumn: { params: ['columnNumber'] },
      RemoveRow: { params: ['rowNumber'] },
      WriteCell: { params: ['cellReference', 'value'] },
      WriteColumn: { params: ['columnNumber', 'columnList'] },
      WriteRange: { params: ['cellRange', 'data'] },
      WriteRow: { params: ['rowNumber', 'rowList'] },
    },
  },

  // ==========================================================================
  // CONNECTIVITY
  // ==========================================================================

  Web: {
    type: 'Web',
    version: '9',
    category: 'connectivity',
    icon: '🌐',
    defaultName: 'Web',
    isVisible: false,
    isLayout: false,
    properties: {
      Url: { type: 'string', default: '' },
      RequestHeaders: { type: 'list', default: '' },
      AllowCookies: { type: 'boolean', default: 'False' },
      SaveResponse: { type: 'boolean', default: 'False' },
      ResponseFileName: { type: 'string', default: '' },
      Timeout: { type: 'number', default: '0' },
    },
    events: ['GotText', 'GotFile', 'TimedOut'],
    methods: {
      Get: { params: [] },
      PostText: { params: ['text'] },
      PostTextWithEncoding: { params: ['text', 'encoding'] },
      PostFile: { params: ['path'] },
      PutText: { params: ['text'] },
      PutTextWithEncoding: { params: ['text', 'encoding'] },
      PutFile: { params: ['path'] },
      PatchText: { params: ['text'] },
      PatchTextWithEncoding: { params: ['text', 'encoding'] },
      Delete: { params: [] },
      BuildRequestData: { params: ['list'] },
      UriEncode: { params: ['text'] },
      UriDecode: { params: ['text'] },
      JsonObjectEncode: { params: ['jsonObject'] },
      JsonTextDecode: { params: ['jsonText'] },
      JsonTextDecodeWithDictionaries: { params: ['jsonText'] },
      XmlTextDecode: { params: ['xmlText'] },
      XmlTextDecodeAsDictionary: { params: ['xmlText'] },
      HtmlTextDecode: { params: ['htmlText'] },
    },
  },

  ActivityStarter: {
    type: 'ActivityStarter',
    version: '6',
    category: 'connectivity',
    icon: '🚀',
    defaultName: 'ActivityStarter',
    isVisible: false,
    isLayout: false,
    properties: {
      Action: { type: 'string', default: '' },
      ActivityClass: { type: 'string', default: '' },
      ActivityPackage: { type: 'string', default: '' },
      DataUri: { type: 'string', default: '' },
      DataType: { type: 'string', default: '' },
      ExtraKey: { type: 'string', default: '' },
      ExtraValue: { type: 'string', default: '' },
      Extras: { type: 'list', default: '' },
      ResultName: { type: 'string', default: '' },
      ResultType: { type: 'string', default: '' },
      ResultUri: { type: 'string', default: '' },
    },
    events: ['AfterActivity', 'ActivityCanceled'],
    methods: {
      StartActivity: { params: [] },
      ResolveActivity: { params: [] },
    },
  },

  BluetoothClient: {
    type: 'BluetoothClient',
    version: '8',
    category: 'connectivity',
    icon: '🔵',
    defaultName: 'BluetoothClient',
    isVisible: false,
    isLayout: false,
    properties: {
      AddressesAndNames: { type: 'list', default: '' },
      CharacterEncoding: { type: 'string', default: 'UTF-8' },
      DelimiterByte: { type: 'number', default: '0' },
      HighByteFirst: { type: 'boolean', default: 'False' },
      Secure: { type: 'boolean', default: 'True' },
    },
    events: [],
    methods: {
      Connect: { params: ['address'] },
      ConnectWithUUID: { params: ['address', 'uuid'] },
      Disconnect: { params: [] },
      IsDevicePaired: { params: ['address'] },
      Send1ByteNumber: { params: ['number'] },
      Send2ByteNumber: { params: ['number'] },
      Send4ByteNumber: { params: ['number'] },
      SendBytes: { params: ['list'] },
      SendText: { params: ['text'] },
      ReceiveSigned1ByteNumber: { params: [] },
      ReceiveUnsigned1ByteNumber: { params: [] },
      ReceiveSigned2ByteNumber: { params: [] },
      ReceiveUnsigned2ByteNumber: { params: [] },
      ReceiveSigned4ByteNumber: { params: [] },
      ReceiveUnsigned4ByteNumber: { params: [] },
      ReceiveSignedBytes: { params: ['numberOfBytes'] },
      ReceiveUnsignedBytes: { params: ['numberOfBytes'] },
      ReceiveText: { params: ['numberOfBytes'] },
      BytesAvailableToReceive: { params: [] },
      IsConnected: { params: [] },
    },
  },

  BluetoothServer: {
    type: 'BluetoothServer',
    version: '5',
    category: 'connectivity',
    icon: '🔷',
    defaultName: 'BluetoothServer',
    isVisible: false,
    isLayout: false,
    properties: {
      CharacterEncoding: { type: 'string', default: 'UTF-8' },
      DelimiterByte: { type: 'number', default: '0' },
      HighByteFirst: { type: 'boolean', default: 'False' },
      Secure: { type: 'boolean', default: 'True' },
    },
    events: ['ConnectionAccepted'],
    methods: {
      AcceptConnection: { params: ['serviceName'] },
      AcceptConnectionWithUUID: { params: ['serviceName', 'uuid'] },
      StopAccepting: { params: [] },
      Disconnect: { params: [] },
      Send1ByteNumber: { params: ['number'] },
      Send2ByteNumber: { params: ['number'] },
      Send4ByteNumber: { params: ['number'] },
      SendBytes: { params: ['list'] },
      SendText: { params: ['text'] },
      ReceiveSigned1ByteNumber: { params: [] },
      ReceiveUnsigned1ByteNumber: { params: [] },
      ReceiveSigned2ByteNumber: { params: [] },
      ReceiveUnsigned2ByteNumber: { params: [] },
      ReceiveSigned4ByteNumber: { params: [] },
      ReceiveUnsigned4ByteNumber: { params: [] },
      ReceiveSignedBytes: { params: ['numberOfBytes'] },
      ReceiveUnsignedBytes: { params: ['numberOfBytes'] },
      ReceiveText: { params: ['numberOfBytes'] },
      BytesAvailableToReceive: { params: [] },
      IsConnected: { params: [] },
    },
  },

  Serial: {
    type: 'Serial',
    version: '1',
    category: 'connectivity',
    icon: '🔌',
    defaultName: 'Serial',
    isVisible: false,
    isLayout: false,
    properties: {
      BaudRate: { type: 'number', default: '9600' },
      BufferSize: { type: 'number', default: '4096' },
      IsInitialized: { type: 'boolean', default: 'False' },
      IsOpen: { type: 'boolean', default: 'False' },
    },
    events: [],
    methods: {
      CloseSerial: { params: [] },
      InitializeSerial: { params: [] },
      OpenSerial: { params: [] },
      PrintSerial: { params: ['data'] },
      ReadSerial: { params: [] },
      WriteSerial: { params: ['data'] },
    },
  },

  // ==========================================================================
  // MAPS
  // ==========================================================================

  Map: {
    type: 'Map',
    version: '6',
    category: 'maps',
    icon: '🗺️',
    defaultName: 'Map',
    isVisible: true,
    isLayout: true,
    properties: {
      CenterFromString: { type: 'string', default: '' },
      EnablePan: { type: 'boolean', default: 'True' },
      EnableRotation: { type: 'boolean', default: 'True' },
      EnableZoom: { type: 'boolean', default: 'True' },
      Height: { type: 'length', default: '200' },
      Width: { type: 'length', default: '-2' },
      Latitude: { type: 'number', default: '42.359144' },
      Longitude: { type: 'number', default: '-71.093612' },
      MapType: { type: 'number', default: '1' },
      Rotation: { type: 'number', default: '0' },
      ScaleUnits: { type: 'number', default: '1' },
      ShowCompass: { type: 'boolean', default: 'False' },
      ShowUser: { type: 'boolean', default: 'False' },
      ShowZoom: { type: 'boolean', default: 'False' },
      ZoomLevel: { type: 'number', default: '13' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['BoundsChange', 'CenterChanged', 'DoubleTapAtPoint', 'FeatureClick',
             'FeatureDrag', 'FeatureLongClick', 'FeatureStartDrag', 'FeatureStopDrag',
             'GotFeatures', 'InvalidPoint', 'LongPressAtPoint', 'Ready',
             'TapAtPoint', 'ZoomChange'],
    methods: {
      CreateMarker: { params: ['latitude', 'longitude'] },
      FeatureFromDescription: { params: ['description'] },
      LoadFromURL: { params: ['url'] },
      PanTo: { params: ['latitude', 'longitude', 'zoom'] },
      Save: { params: ['path'] },
    },
  },

  Marker: {
    type: 'Marker',
    version: '3',
    category: 'maps',
    icon: '📍',
    defaultName: 'Marker',
    isVisible: false,
    isLayout: false,
    properties: {
      AnchorHorizontal: { type: 'number', default: '3' },
      AnchorVertical: { type: 'number', default: '3' },
      Description: { type: 'string', default: '' },
      Draggable: { type: 'boolean', default: 'False' },
      EnableInfobox: { type: 'boolean', default: 'False' },
      FillColor: { type: 'color', default: '&HFFFF0000' },
      FillOpacity: { type: 'number', default: '1' },
      Height: { type: 'length', default: '-1' },
      ImageAsset: { type: 'string', default: '' },
      Latitude: { type: 'number', default: '0' },
      Longitude: { type: 'number', default: '0' },
      StrokeColor: { type: 'color', default: '&HFF000000' },
      StrokeOpacity: { type: 'number', default: '1' },
      StrokeWidth: { type: 'number', default: '1' },
      Title: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['Click', 'Drag', 'LongClick', 'StartDrag', 'StopDrag'],
    methods: {
      BearingToFeature: { params: ['mapFeature', 'centroids'] },
      BearingToPoint: { params: ['latitude', 'longitude', 'centroids'] },
      DistanceToFeature: { params: ['mapFeature', 'centroids'] },
      DistanceToPoint: { params: ['latitude', 'longitude', 'centroids'] },
      HideInfobox: { params: [] },
      SetLocation: { params: ['latitude', 'longitude'] },
      ShowInfobox: { params: [] },
    },
  },

  Circle: {
    type: 'Circle',
    version: '2',
    category: 'maps',
    icon: '⭕',
    defaultName: 'Circle',
    isVisible: false,
    isLayout: false,
    properties: {
      Description: { type: 'string', default: '' },
      Draggable: { type: 'boolean', default: 'False' },
      EnableInfobox: { type: 'boolean', default: 'False' },
      FillColor: { type: 'color', default: '&HFFFF0000' },
      FillOpacity: { type: 'number', default: '1' },
      Latitude: { type: 'number', default: '0' },
      Longitude: { type: 'number', default: '0' },
      Radius: { type: 'number', default: '0' },
      StrokeColor: { type: 'color', default: '&HFF000000' },
      StrokeOpacity: { type: 'number', default: '1' },
      StrokeWidth: { type: 'number', default: '1' },
      Title: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Click', 'Drag', 'LongClick', 'StartDrag', 'StopDrag'],
    methods: {
      DistanceToFeature: { params: ['mapFeature', 'centroids'] },
      DistanceToPoint: { params: ['latitude', 'longitude', 'centroid'] },
      HideInfobox: { params: [] },
      SetLocation: { params: ['latitude', 'longitude'] },
      ShowInfobox: { params: [] },
    },
  },

  Rectangle: {
    type: 'Rectangle',
    version: '2',
    category: 'maps',
    icon: '⬜',
    defaultName: 'Rectangle',
    isVisible: false,
    isLayout: false,
    properties: {
      Description: { type: 'string', default: '' },
      Draggable: { type: 'boolean', default: 'False' },
      EastLongitude: { type: 'number', default: '0' },
      EnableInfobox: { type: 'boolean', default: 'False' },
      FillColor: { type: 'color', default: '&HFFFF0000' },
      FillOpacity: { type: 'number', default: '1' },
      NorthLatitude: { type: 'number', default: '0' },
      SouthLatitude: { type: 'number', default: '0' },
      StrokeColor: { type: 'color', default: '&HFF000000' },
      StrokeOpacity: { type: 'number', default: '1' },
      StrokeWidth: { type: 'number', default: '1' },
      Title: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      WestLongitude: { type: 'number', default: '0' },
    },
    events: ['Click', 'Drag', 'LongClick', 'StartDrag', 'StopDrag'],
    methods: {
      Bounds: { params: [] },
      Center: { params: [] },
      DistanceToFeature: { params: ['mapFeature', 'centroids'] },
      DistanceToPoint: { params: ['latitude', 'longitude', 'centroid'] },
      HideInfobox: { params: [] },
      SetCenter: { params: ['latitude', 'longitude'] },
      ShowInfobox: { params: [] },
    },
  },

  Polygon: {
    type: 'Polygon',
    version: '2',
    category: 'maps',
    icon: '🔷',
    defaultName: 'Polygon',
    isVisible: false,
    isLayout: false,
    properties: {
      Description: { type: 'string', default: '' },
      Draggable: { type: 'boolean', default: 'False' },
      EnableInfobox: { type: 'boolean', default: 'False' },
      FillColor: { type: 'color', default: '&HFFFF0000' },
      FillOpacity: { type: 'number', default: '1' },
      HolePoints: { type: 'list', default: '' },
      HolePointsFromString: { type: 'string', default: '' },
      Points: { type: 'list', default: '' },
      PointsFromString: { type: 'string', default: '' },
      StrokeColor: { type: 'color', default: '&HFF000000' },
      StrokeOpacity: { type: 'number', default: '1' },
      StrokeWidth: { type: 'number', default: '1' },
      Title: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Click', 'Drag', 'LongClick', 'StartDrag', 'StopDrag'],
    methods: {
      Centroid: { params: [] },
      DistanceToFeature: { params: ['mapFeature', 'centroids'] },
      DistanceToPoint: { params: ['latitude', 'longitude', 'centroid'] },
      HideInfobox: { params: [] },
      ShowInfobox: { params: [] },
    },
  },

  LineString: {
    type: 'LineString',
    version: '2',
    category: 'maps',
    icon: '〰️',
    defaultName: 'LineString',
    isVisible: false,
    isLayout: false,
    properties: {
      Description: { type: 'string', default: '' },
      Draggable: { type: 'boolean', default: 'False' },
      EnableInfobox: { type: 'boolean', default: 'False' },
      Points: { type: 'list', default: '' },
      PointsFromString: { type: 'string', default: '' },
      StrokeColor: { type: 'color', default: '&HFF000000' },
      StrokeOpacity: { type: 'number', default: '1' },
      StrokeWidth: { type: 'number', default: '3' },
      Title: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Click', 'Drag', 'LongClick', 'StartDrag', 'StopDrag'],
    methods: {
      DistanceToFeature: { params: ['mapFeature', 'centroids'] },
      DistanceToPoint: { params: ['latitude', 'longitude', 'centroid'] },
      HideInfobox: { params: [] },
      ShowInfobox: { params: [] },
    },
  },

  FeatureCollection: {
    type: 'FeatureCollection',
    version: '2',
    category: 'maps',
    icon: '📦',
    defaultName: 'FeatureCollection',
    isVisible: false,
    isLayout: true,
    properties: {
      FeaturesFromGeoJSON: { type: 'string', default: '' },
      Height: { type: 'length', default: '-1' },
      Source: { type: 'string', default: '' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-1' },
    },
    events: ['FeatureClick', 'FeatureDrag', 'FeatureLongClick', 'FeatureStartDrag', 'FeatureStopDrag', 'GotFeatures', 'LoadError'],
    methods: {
      FeatureFromDescription: { params: ['description'] },
      LoadFromURL: { params: ['url'] },
    },
  },

  Navigation: {
    type: 'Navigation',
    version: '2',
    category: 'maps',
    icon: '🧭',
    defaultName: 'Navigation',
    isVisible: false,
    isLayout: false,
    properties: {
      ApiKey: { type: 'string', default: '' },
      EndLatitude: { type: 'number', default: '0' },
      EndLocation: { type: 'string', default: '' },
      EndLongitude: { type: 'number', default: '0' },
      Language: { type: 'string', default: 'en' },
      ResponseContent: { type: 'string', default: '' },
      StartLatitude: { type: 'number', default: '0' },
      StartLocation: { type: 'string', default: '' },
      StartLongitude: { type: 'number', default: '0' },
      TransportationMethod: { type: 'string', default: 'foot-walking' },
    },
    events: ['GotDirections'],
    methods: {
      RequestDirections: { params: [] },
    },
  },

  // ==========================================================================
  // CHARTS
  // ==========================================================================

  Chart: {
    type: 'Chart',
    version: '4',
    category: 'charts',
    icon: '📊',
    defaultName: 'Chart',
    isVisible: true,
    isLayout: false,
    properties: {
      BackgroundColor: { type: 'color', default: '&HFFFFFFFF' },
      Description: { type: 'string', default: '' },
      GridEnabled: { type: 'boolean', default: 'True' },
      Height: { type: 'length', default: '200' },
      Labels: { type: 'list', default: '' },
      LabelsFromString: { type: 'string', default: '' },
      LegendEnabled: { type: 'boolean', default: 'True' },
      PieRadius: { type: 'number', default: '100' },
      Type: { type: 'number', default: '0' },
      Visible: { type: 'boolean', default: 'True' },
      Width: { type: 'length', default: '-2' },
      XFromZero: { type: 'boolean', default: 'False' },
      YFromZero: { type: 'boolean', default: 'False' },
    },
    events: ['EntryClick'],
    methods: {
      SetDomain: { params: ['minimum', 'maximum'] },
      SetRange: { params: ['minimum', 'maximum'] },
    },
  },

  ChartData2D: {
    type: 'ChartData2D',
    version: '2',
    category: 'charts',
    icon: '📈',
    defaultName: 'ChartData2D',
    isVisible: false,
    isLayout: false,
    properties: {
      Color: { type: 'color', default: '&HFF000000' },
      Colors: { type: 'list', default: '' },
      DataFileXColumn: { type: 'string', default: '' },
      DataFileYColumn: { type: 'string', default: '' },
      DataSourceKey: { type: 'string', default: '' },
      ElementsFromPairs: { type: 'string', default: '' },
      Label: { type: 'string', default: '' },
      LineType: { type: 'string', default: 'linear' },
      PointShape: { type: 'string', default: 'circle' },
      SpreadsheetUseHeaders: { type: 'boolean', default: 'False' },
      SpreadsheetXColumn: { type: 'string', default: '' },
      SpreadsheetYColumn: { type: 'string', default: '' },
      WebXColumn: { type: 'string', default: '' },
      WebYColumn: { type: 'string', default: '' },
    },
    events: ['EntryClick'],
    methods: {
      AddEntry: { params: ['x', 'y'] },
      ChangeDataSource: { params: ['source', 'keyValue'] },
      Clear: { params: [] },
      DoesEntryExist: { params: ['x', 'y'] },
      GetAllEntries: { params: [] },
      GetEntriesWithXValue: { params: ['x'] },
      GetEntriesWithYValue: { params: ['y'] },
      ImportFromCloudDB: { params: ['cloudDB', 'tag'] },
      ImportFromDataFile: { params: ['dataFile', 'xValueColumn', 'yValueColumn'] },
      ImportFromList: { params: ['list'] },
      ImportFromSpreadsheet: { params: ['spreadsheet', 'xColumn', 'yColumn', 'useHeaders'] },
      ImportFromTinyDB: { params: ['tinyDB', 'tag'] },
      ImportFromWeb: { params: ['web', 'xValueColumn', 'yValueColumn'] },
      RemoveDataSource: { params: [] },
      RemoveEntry: { params: ['x', 'y'] },
    },
  },

  Trendline: {
    type: 'Trendline',
    version: '1',
    category: 'charts',
    icon: '📉',
    defaultName: 'Trendline',
    isVisible: false,
    isLayout: false,
    properties: {
      Color: { type: 'color', default: '&HFF000000' },
      Extend: { type: 'boolean', default: 'False' },
      Model: { type: 'string', default: 'Linear' },
      StrokeWidth: { type: 'number', default: '2' },
      Visible: { type: 'boolean', default: 'True' },
    },
    events: ['Updated'],
    methods: {
      GetResultValue: { params: ['value'] },
    },
  },

  // ==========================================================================
  // DATA SCIENCE
  // ==========================================================================

  AnomalyDetection: {
    type: 'AnomalyDetection',
    version: '2',
    category: 'datascience',
    icon: '🔍',
    defaultName: 'AnomalyDetection',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: [],
    methods: {
      CleanData: { params: ['anomaly', 'xList', 'yList'] },
      DetectAnomalies: { params: ['dataList', 'threshold'] },
      DetectAnomaliesInChartData: { params: ['chartData', 'threshold'] },
    },
  },

  Regression: {
    type: 'Regression',
    version: '2',
    category: 'datascience',
    icon: '📐',
    defaultName: 'Regression',
    isVisible: false,
    isLayout: false,
    properties: {},
    events: [],
    methods: {
      CalculateLineOfBestFitValue: { params: ['xList', 'yList', 'value'] },
    },
  },

  // ==========================================================================
  // EXPERIMENTAL
  // ==========================================================================

  ChatBot: {
    type: 'ChatBot',
    version: '5',
    category: 'experimental',
    icon: '🤖',
    defaultName: 'ChatBot',
    isVisible: false,
    isLayout: false,
    properties: {
      ApiKey: { type: 'string', default: '' },
      Model: { type: 'string', default: '' },
      Provider: { type: 'string', default: 'chatgpt' },
      System: { type: 'string', default: '' },
      Token: { type: 'string', default: '' },
    },
    events: ['ErrorOccurred', 'GotResponse'],
    methods: {
      Converse: { params: ['question'] },
      ConverseWithImage: { params: ['question', 'imageSource'] },
      ResetConversation: { params: [] },
    },
  },

  ImageBot: {
    type: 'ImageBot',
    version: '2',
    category: 'experimental',
    icon: '🎨',
    defaultName: 'ImageBot',
    isVisible: false,
    isLayout: false,
    properties: {
      ApiKey: { type: 'string', default: '' },
      InvertMask: { type: 'boolean', default: 'False' },
      Size: { type: 'number', default: '256' },
      Token: { type: 'string', default: '' },
    },
    events: ['ErrorOccurred', 'ImageCreated'],
    methods: {
      CreateImage: { params: ['description'] },
      EditImage: { params: ['imageSource', 'prompt'] },
      EditImageWithMask: { params: ['imageSource', 'maskSource', 'prompt'] },
    },
  },

  // ==========================================================================
  // LEGO MINDSTORMS
  // ==========================================================================

  Ev3ColorSensor: {
    type: 'Ev3ColorSensor', version: '2', category: 'lego', icon: '🎨',
    defaultName: 'Ev3ColorSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      ColorChangedEventEnabled: { type: 'boolean', default: 'False' },
      Mode: { type: 'string', default: 'reflected' },
      SensorPort: { type: 'string', default: '1' },
      TopOfRange: { type: 'number', default: '100' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'ColorChanged', 'WithinRange'],
    methods: { GetColorCode: { params: [] }, GetColorName: { params: [] }, GetLightLevel: { params: [] } },
  },

  Ev3Commands: {
    type: 'Ev3Commands', version: '1', category: 'lego', icon: '🎮',
    defaultName: 'Ev3Commands', isVisible: false, isLayout: false,
    properties: {},
    events: [],
    methods: {
      GetBatteryCurrent: { params: [] }, GetBatteryVoltage: { params: [] },
      GetFirmwareBuild: { params: [] }, GetFirmwareVersion: { params: [] },
      GetHardwareVersion: { params: [] }, GetOSBuild: { params: [] },
      GetOSVersion: { params: [] }, KeepAlive: { params: ['minutes'] },
    },
  },

  Ev3GyroSensor: {
    type: 'Ev3GyroSensor', version: '2', category: 'lego', icon: '🌀',
    defaultName: 'Ev3GyroSensor', isVisible: false, isLayout: false,
    properties: {
      Mode: { type: 'string', default: 'angle' },
      SensorPort: { type: 'string', default: '1' },
      SensorValueChangedEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['SensorValueChanged'],
    methods: { GetSensorValue: { params: [] } },
  },

  Ev3Motors: {
    type: 'Ev3Motors', version: '1', category: 'lego', icon: '⚙️',
    defaultName: 'Ev3Motors', isVisible: false, isLayout: false,
    properties: {
      EnableSpeedRegulation: { type: 'boolean', default: 'True' },
      MotorPorts: { type: 'string', default: 'A' },
      ReverseDirection: { type: 'boolean', default: 'False' },
      StopBeforeDisconnect: { type: 'boolean', default: 'True' },
      TachoCountChangedEventEnabled: { type: 'boolean', default: 'False' },
      WheelDiameter: { type: 'number', default: '4.32' },
    },
    events: ['TachoCountChanged'],
    methods: {
      GetTachoCount: { params: [] }, ResetTachoCount: { params: [] },
      RotateInDistance: { params: ['power', 'distance', 'useBrake'] },
      RotateInDuration: { params: ['power', 'milliseconds', 'useBrake'] },
      RotateInTachoCounts: { params: ['power', 'tachoCounts', 'useBrake'] },
      RotateIndefinitely: { params: ['power'] },
      RotateSyncInDistance: { params: ['power', 'distance', 'turnRatio', 'useBrake'] },
      RotateSyncInDuration: { params: ['power', 'milliseconds', 'turnRatio', 'useBrake'] },
      RotateSyncInTachoCounts: { params: ['power', 'tachoCounts', 'turnRatio', 'useBrake'] },
      RotateSyncIndefinitely: { params: ['power', 'turnRatio'] },
      Stop: { params: ['useBrake'] }, ToggleDirection: { params: [] },
    },
  },

  Ev3Sound: {
    type: 'Ev3Sound', version: '1', category: 'lego', icon: '🔊',
    defaultName: 'Ev3Sound', isVisible: false, isLayout: false,
    properties: {}, events: [],
    methods: { PlayTone: { params: ['volume', 'frequency', 'milliseconds'] }, StopSound: { params: [] } },
  },

  Ev3TouchSensor: {
    type: 'Ev3TouchSensor', version: '1', category: 'lego', icon: '👆',
    defaultName: 'Ev3TouchSensor', isVisible: false, isLayout: false,
    properties: {
      PressedEventEnabled: { type: 'boolean', default: 'False' },
      ReleasedEventEnabled: { type: 'boolean', default: 'False' },
      SensorPort: { type: 'string', default: '1' },
    },
    events: ['Pressed', 'Released'],
    methods: { IsPressed: { params: [] } },
  },

  Ev3UI: {
    type: 'Ev3UI', version: '1', category: 'lego', icon: '🖥️',
    defaultName: 'Ev3UI', isVisible: false, isLayout: false,
    properties: {}, events: [],
    methods: {
      DrawCircle: { params: ['color', 'x', 'y', 'radius', 'fill'] },
      DrawIcon: { params: ['color', 'x', 'y', 'type', 'no'] },
      DrawLine: { params: ['color', 'x1', 'y1', 'x2', 'y2'] },
      DrawPoint: { params: ['color', 'x', 'y'] },
      DrawRect: { params: ['color', 'x', 'y', 'width', 'height', 'fill'] },
      FillScreen: { params: ['color'] },
    },
  },

  Ev3UltrasonicSensor: {
    type: 'Ev3UltrasonicSensor', version: '2', category: 'lego', icon: '📡',
    defaultName: 'Ev3UltrasonicSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      SensorPort: { type: 'string', default: '1' },
      TopOfRange: { type: 'number', default: '100' },
      Unit: { type: 'string', default: 'cm' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'WithinRange'],
    methods: { GetDistance: { params: [] } },
  },

  NxtColorSensor: {
    type: 'NxtColorSensor', version: '1', category: 'lego', icon: '🎨',
    defaultName: 'NxtColorSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      ColorChangedEventEnabled: { type: 'boolean', default: 'False' },
      DetectColor: { type: 'boolean', default: 'True' },
      GenerateColor: { type: 'number', default: '0' },
      SensorPort: { type: 'string', default: '3' },
      TopOfRange: { type: 'number', default: '100' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'ColorChanged', 'WithinRange'],
    methods: { GetColor: { params: [] }, GetLightLevel: { params: [] } },
  },

  NxtDirectCommands: {
    type: 'NxtDirectCommands', version: '2', category: 'lego', icon: '🎮',
    defaultName: 'NxtDirectCommands', isVisible: false, isLayout: false,
    properties: {}, events: [],
    methods: {
      DeleteFile: { params: ['fileName'] }, DownloadFile: { params: ['source', 'destination'] },
      GetBatteryLevel: { params: [] }, GetBrickName: { params: [] },
      GetCurrentProgramName: { params: [] }, GetFirmwareVersion: { params: [] },
      GetInputValues: { params: ['sensorPortLetter'] }, GetOutputState: { params: ['motorPortLetter'] },
      KeepAlive: { params: [] }, ListFiles: { params: ['wildcard'] },
      LsGetStatus: { params: ['sensorPortLetter'] }, LsRead: { params: ['sensorPortLetter'] },
      LsWrite: { params: ['sensorPortLetter', 'list', 'rxDataLength'] },
      MessageRead: { params: ['mailbox'] }, MessageWrite: { params: ['mailbox', 'message'] },
      PlaySoundFile: { params: ['fileName'] }, PlayTone: { params: ['frequencyHz', 'durationMs'] },
      ResetInputScaledValue: { params: ['sensorPortLetter'] },
      ResetMotorPosition: { params: ['motorPortLetter', 'relative'] },
      SetBrickName: { params: ['name'] },
      SetInputMode: { params: ['sensorPortLetter', 'sensorType', 'sensorMode'] },
      SetOutputState: { params: ['motorPortLetter', 'power', 'mode', 'regulationMode', 'turnRatio', 'runState', 'tachoLimit'] },
      StartProgram: { params: ['programName'] }, StopProgram: { params: [] }, StopSoundPlayback: { params: [] },
    },
  },

  NxtDrive: {
    type: 'NxtDrive', version: '1', category: 'lego', icon: '🚗',
    defaultName: 'NxtDrive', isVisible: false, isLayout: false,
    properties: {
      DriveMotors: { type: 'string', default: 'CB' },
      StopBeforeDisconnect: { type: 'boolean', default: 'True' },
      WheelDiameter: { type: 'number', default: '4.32' },
    },
    events: [],
    methods: {
      MoveBackward: { params: ['power', 'distance'] }, MoveBackwardIndefinitely: { params: ['power'] },
      MoveForward: { params: ['power', 'distance'] }, MoveForwardIndefinitely: { params: ['power'] },
      Stop: { params: [] }, TurnClockwiseIndefinitely: { params: ['power'] },
      TurnCounterClockwiseIndefinitely: { params: ['power'] },
    },
  },

  NxtLightSensor: {
    type: 'NxtLightSensor', version: '1', category: 'lego', icon: '💡',
    defaultName: 'NxtLightSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      GenerateLight: { type: 'boolean', default: 'False' },
      SensorPort: { type: 'string', default: '3' },
      TopOfRange: { type: 'number', default: '100' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'WithinRange'],
    methods: { GetLightLevel: { params: [] } },
  },

  NxtSoundSensor: {
    type: 'NxtSoundSensor', version: '1', category: 'lego', icon: '🔉',
    defaultName: 'NxtSoundSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      SensorPort: { type: 'string', default: '2' },
      TopOfRange: { type: 'number', default: '100' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'WithinRange'],
    methods: { GetSoundLevel: { params: [] } },
  },

  NxtTouchSensor: {
    type: 'NxtTouchSensor', version: '1', category: 'lego', icon: '👆',
    defaultName: 'NxtTouchSensor', isVisible: false, isLayout: false,
    properties: {
      PressedEventEnabled: { type: 'boolean', default: 'False' },
      ReleasedEventEnabled: { type: 'boolean', default: 'False' },
      SensorPort: { type: 'string', default: '1' },
    },
    events: ['Pressed', 'Released'],
    methods: { IsPressed: { params: [] } },
  },

  NxtUltrasonicSensor: {
    type: 'NxtUltrasonicSensor', version: '1', category: 'lego', icon: '📡',
    defaultName: 'NxtUltrasonicSensor', isVisible: false, isLayout: false,
    properties: {
      AboveRangeEventEnabled: { type: 'boolean', default: 'False' },
      BelowRangeEventEnabled: { type: 'boolean', default: 'False' },
      BottomOfRange: { type: 'number', default: '0' },
      SensorPort: { type: 'string', default: '4' },
      TopOfRange: { type: 'number', default: '100' },
      WithinRangeEventEnabled: { type: 'boolean', default: 'False' },
    },
    events: ['AboveRange', 'BelowRange', 'WithinRange'],
    methods: { GetDistance: { params: [] } },
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Returns an object of default property values for the given component type.
 * Only includes properties that have a non-empty default value.
 */
export function getDefaultProperties(componentType) {
  const def = COMPONENTS[componentType];
  if (!def) return {};
  const props = {};
  for (const [key, val] of Object.entries(def.properties)) {
    if (val.default !== undefined && val.default !== '') {
      props[key] = val.default;
    }
  }
  return props;
}

/**
 * Generates a unique ID string in the format used by App Inventor components.
 */
export function generateUuid() {
  return '-' + (crypto.getRandomValues(new Uint32Array(1))[0] % 1000000000);
}
